package xyz.magicrampagecompanion;

public enum ElixirType {
    ARCANE_PRECISION_TONIC,
    ELIXIR_OF_DUPLICATION,
    FORBIDDEN_FLOWERS_EXTRACT,
    INSTANT_CHARGE_BLAST,
    INSTANT_DARK_TWIN,
    INSTANT_GUST,
    INSTANT_RADIANT_SHIELD,
    INSTANT_THUNDER_WAVE,
    LEVITATION_LIQUEUR,
    MONSTERS_JUICE,
    MOONJUMP_MIXTURE,
    PEPPER_BREW,
    STARLIGHT_SUPERTONIC,
    TONIC_OF_INVULNERABILITY,
    UMBRANIAN_WATER,
    UNKNOWN
}
