package xyz.magicrampagecompanion;

import android.content.Context;
import java.util.ArrayList;
import java.util.List;

public class ItemData {
    public static final List<Weapon> staffList = new ArrayList<>();
    public static final List<Weapon> daggerList = new ArrayList<>();
    public static final List<Weapon> axeList = new ArrayList<>();
    public static final List<Weapon> spearList = new ArrayList<>();
    public static final List<Weapon> hammerList = new ArrayList<>();
    public static final List<Weapon> swordList = new ArrayList<>();
    public static final List<Armor> armorList = new ArrayList<>();
    public static final List<Ring> ringList = new ArrayList<>();
    public static final List<Enemy> enemyList = new ArrayList<>();
    public static final List<CharacterClass> classList = new ArrayList<>();
    private static String str(Context ctx, int resId) {
        return ctx.getString(resId);
    }

    public static void init(Context context) {
        // Swords
        swordList.add(new Weapon(str(context, R.string.recruit_sword), WeaponTypes.SWORD, Elements.NEUTRAL, 7, 12, 1, 0, 4, 0, R.drawable.sword_recruit_fire_sword, 650, 0, false, false, false, false));
        swordList.add(new Weapon(str(context, R.string.fire_sword), WeaponTypes.SWORD, Elements.FIRE, 8, 13, 1, 0, 4, 0, R.drawable.sword_recruit_fire_sword, 700, 0, false, false, false, false));
        swordList.add(new Weapon(str(context, R.string.steel_blade), WeaponTypes.SWORD, Elements.NEUTRAL, 11, 18, 1, 15, 5, 0, R.drawable.sword_steel_blade, 650, 0, false, false, false, false));
        swordList.add(new Weapon(str(context, R.string.master_sword), WeaponTypes.SWORD, Elements.AIR, 14, 24, 1, 20, 4, 2, R.drawable.sword_master_sword, 650, 0, false, false, false, false));
        swordList.add(new Weapon(str(context, R.string.vorpal_sword), WeaponTypes.SWORD, Elements.NEUTRAL, 25, 43, 1, 40, 6, 0, R.drawable.sword_vorpal_sword, 400, 0, false, false, false, false));
        swordList.add(new Weapon(str(context, R.string.pirate_sword), WeaponTypes.SWORD, Elements.NEUTRAL, 26, 44, 1, 10, 6, 4, R.drawable.sword_pirate_sword, 500, 0, false, false, false, false));
        swordList.add(new Weapon(str(context, R.string.nobel_sword), WeaponTypes.SWORD, Elements.NEUTRAL, 29, 49, 1, 30, 4, 0, R.drawable.sword_nobel_sword, 400, 0, false, false, false, false));
        swordList.add(new Weapon(str(context, R.string.bunny_sword), WeaponTypes.SWORD, Elements.EARTH, 49, 49, 1, 0, 0, 20, R.drawable.sword_bunny_sword, 500, 1, false, false, false, false));
        swordList.add(new Weapon(str(context, R.string.leaf_sword), WeaponTypes.SWORD, Elements.EARTH, 23, 72, 9, 25, 3, 2, R.drawable.sword_leaf_sword, 400, 0, false, false, false, false));
        swordList.add(new Weapon(str(context, R.string.magicsaber), WeaponTypes.SWORD, Elements.LIGHT, 27, 111, 13, 0, 3, 3, R.drawable.sword_magicsaber, 600, 0, false, false, false, false));
        swordList.add(new Weapon(str(context, R.string.darkskull_sword), WeaponTypes.SWORD, Elements.DARKNESS, 32, 124, 12, 20, 4, 0, R.drawable.sword_fireskull_darkskull_sword, 600, 0, false, false, false, false));
        swordList.add(new Weapon(str(context, R.string.umbranian_long_sword), WeaponTypes.SWORD, Elements.AIR, 38, 129, 10, 45, 7, 2, R.drawable.sword_umbranian_long_sword, 450, 0, false, false, false, false));
        swordList.add(new Weapon(str(context, R.string.umbranian_short_sword), WeaponTypes.SWORD, Elements.NEUTRAL, 32, 131, 13, 50, 7, 0, R.drawable.sword_umbranian_short_sword, 300, 0, false, false, false, false));
        swordList.add(new Weapon(str(context, R.string.fireskull_sword), WeaponTypes.SWORD, Elements.FIRE, 36, 139, 12, 30, 6, 0, R.drawable.sword_fireskull_darkskull_sword, 500, 0, false, false, false, false));
        swordList.add(new Weapon(str(context, R.string.sword_of_light), WeaponTypes.SWORD, Elements.LIGHT, 40, 145, 11, 0, 5, 2, R.drawable.sword_sword_of_light, 350, 1, true, true, false, false));
        swordList.add(new Weapon(str(context, R.string.throat_cutter), WeaponTypes.SWORD, Elements.DARKNESS, 50, 230, 15, 0, 4, 2, R.drawable.sword_throat_cutter, 500, 0, false, false, false, false));
        swordList.add(new Weapon(str(context, R.string.ice_claw), WeaponTypes.SWORD, Elements.WATER, 66, 303, 15, 40, 5, 2, R.drawable.sword_ice_claw, 500, 0, false, false, false, true));
        swordList.add(new Weapon(str(context, R.string.moonlit_razor), WeaponTypes.SWORD, Elements.NEUTRAL, 80, 329, 13, 40, 6, 3, R.drawable.sword_moonlit_razor, 550, 2, false, false, false, false));
        swordList.add(new Weapon(str(context, R.string.light_piercer), WeaponTypes.SWORD, Elements.LIGHT, 76, 349, 15, 0, 7, 3, R.drawable.sword_light_piercer, 550, 1, false, true, false, false));
        swordList.add(new Weapon(str(context, R.string.air_piercer), WeaponTypes.SWORD, Elements.AIR, 77, 354, 15, 0, 10, 3, R.drawable.sword_air_piercer, 450, 1, false, true, false, false));
        swordList.add(new Weapon(str(context, R.string.abyssal_blade), WeaponTypes.SWORD, Elements.WATER, 77, 354, 15, 40, 4, 2, R.drawable.sword_abyssal_blade, 650, 1, true, true, false, false));
        swordList.add(new Weapon(str(context, R.string.gorgon_blade), WeaponTypes.SWORD, Elements.NEUTRAL, 80, 368, 15, 40, 9, 0, R.drawable.sword_gorgon_blade, 550, 1, true, true, true, false));
        swordList.add(new Weapon(str(context, R.string.air_striker), WeaponTypes.SWORD, Elements.AIR, 85, 391, 15, 40, 5, 5, R.drawable.sword_air_striker, 600, 0, false, true, false, false));
        swordList.add(new Weapon(str(context, R.string.glass_blade), WeaponTypes.SWORD, Elements.NEUTRAL, 85, 391, 15, 15, 7, 3, R.drawable.sword_glass_blade, 550, 1, false, false, false, false));
        swordList.add(new Weapon(str(context, R.string.arachnid_sword), WeaponTypes.SWORD, Elements.NEUTRAL, 86, 395, 15, 20, 4, 6, R.drawable.sword_arachnid_sword, 450, 1, false, true, true, false));
        swordList.add(new Weapon(str(context, R.string.frost_heart), WeaponTypes.SWORD, Elements.DARKNESS, 88, 404, 15, 30, 3, 2, R.drawable.sword_frostheart, 500, 1, false, false, false, true));
        swordList.add(new Weapon(str(context, R.string.volcano_sword), WeaponTypes.SWORD, Elements.FIRE, 89, 409, 15, 25, 5, 0, R.drawable.sword_volcano_sword, 500, 1, false, true, false, false));
        swordList.add(new Weapon(str(context, R.string.cthulhu_blade), WeaponTypes.SWORD, Elements.NEUTRAL, 90, 414, 15, 35, 7, 3, R.drawable.sword_cthulhu_blade, 500, 1, false, true, true, false));
        swordList.add(new Weapon(str(context, R.string.blade_of_the_wicked), WeaponTypes.SWORD, Elements.NEUTRAL, 90, 414, 15, 0, 7, 4, R.drawable.sword_blade_of_the_wicked, 450, 1, true, true, true, false));
        swordList.add(new Weapon(str(context, R.string.goldsteel), WeaponTypes.SWORD, Elements.NEUTRAL, 90, 414, 15, 30, 5, 2, R.drawable.sword_goldsteel, 500, 0, false, false, false, false));
        swordList.add(new Weapon(str(context, R.string.bunny_claymore), WeaponTypes.SWORD, Elements.NEUTRAL, 92, 423, 15, 30, 6, 10, R.drawable.sword_bunny_claymore, 500, 0, false, false, false, false));
        swordList.add(new Weapon(str(context, R.string.golden_needle), WeaponTypes.SWORD, Elements.NEUTRAL, 94, 432, 15, 0, 6, 2, R.drawable.sword_golden_needle, 450, 2, false, false, false, false));
        swordList.add(new Weapon(str(context, R.string.blade_of_rusted_souls), WeaponTypes.SWORD, Elements.NEUTRAL, 99, 455, 15, 30, 3, 0, R.drawable.sword_blade_of_rusted_souls, 500, 1, false, false, false, false));
        swordList.add(new Weapon(str(context, R.string.haunted_slicer), WeaponTypes.SWORD, Elements.DARKNESS, 100, 460, 15, 20, 5, 3, R.drawable.sword_haunted_slicer, 500, 2, false, true, false, false));
        swordList.add(new Weapon(str(context, R.string.all_seeing_sword), WeaponTypes.SWORD, Elements.DARKNESS, 110, 506, 15, 30, 2, 2, R.drawable.sword_all_seeing_sword, 700, 1, true, false, false, false));
        swordList.add(new Weapon(str(context, R.string.sword_of_1000_lies), WeaponTypes.SWORD, Elements.FIRE, 115, 529, 15, 20, 0, 2, R.drawable.sword_sword_of_1000_lies, 850, 1, false, false, false, false));
        swordList.add(new Weapon(str(context, R.string.blade_of_survival), WeaponTypes.SWORD, Elements.NEUTRAL, 120, 552, 15, 40, 0, 0, R.drawable.sword_blade_of_survival, 800, 0, false, true, false, false));
        swordList.add(new Weapon(str(context, R.string.unleashed_kraken), WeaponTypes.SWORD, Elements.WATER, 130, 598, 15, 25, 2, 1, R.drawable.sword_unleashed_kraken, 550, 0, false, true, false, false));

        // Daggers
        daggerList.add(new Weapon(str(context, R.string.iron_dagger), WeaponTypes.DAGGER, Elements.NEUTRAL, 4, 6, 1, 0, 5, 0, R.drawable.dagger_iron_fire_dagger, 450, 0, false, false, false, false));
        daggerList.add(new Weapon(str(context, R.string.fire_dagger), WeaponTypes.DAGGER, Elements.FIRE, 7, 12, 1, 0, 6, 0, R.drawable.dagger_iron_fire_dagger, 600, 0, false, false, false, false));
        daggerList.add(new Weapon(str(context, R.string.machete), WeaponTypes.DAGGER, Elements.NEUTRAL, 8, 13, 1, 0, 7, 0, R.drawable.dagger_machete, 500, 0, false, false, false, false));
        daggerList.add(new Weapon(str(context, R.string.chef_knife), WeaponTypes.DAGGER, Elements.NEUTRAL, 9, 15, 1, 0, 4, 2, R.drawable.dagger_chef_knife, 500, 0, false, false, false, false));
        daggerList.add(new Weapon(str(context, R.string.steel_dagger), WeaponTypes.DAGGER, Elements.NEUTRAL, 16, 27, 1, 0, 6, 3, R.drawable.dagger_steel_dagger, 450, 0, false, false, false, false));
        daggerList.add(new Weapon(str(context, R.string.kunai), WeaponTypes.DAGGER, Elements.DARKNESS, 11, 45, 13, 0, 16, 3, R.drawable.dagger_kunai, 500, 0, false, false, false, false));
        daggerList.add(new Weapon(str(context, R.string.poisoned_dagger), WeaponTypes.DAGGER, Elements.EARTH, 10, 48, 16, 0, 20, 4, R.drawable.dagger_poisoned_dagger, 400, 0, false, false, true, false));
        daggerList.add(new Weapon(str(context, R.string.poisoned_dart), WeaponTypes.DAGGER, Elements.NEUTRAL, 15, 72, 16, 0, 20, 4, R.drawable.dagger_poisoned_dart, 300, 0, false, false, true, false));
        daggerList.add(new Weapon(str(context, R.string.light_dagger), WeaponTypes.DAGGER, Elements.LIGHT, 12, 75, 22, 0, 10, 10, R.drawable.dagger_light_dagger, 400, 0, false, false, false, false));
        daggerList.add(new Weapon(str(context, R.string.gorgon_dagger), WeaponTypes.DAGGER, Elements.EARTH, 24, 98, 3, 30, 15, 2, R.drawable.dagger_gorgon_dagger, 600, 1, true, false, true, false));
        daggerList.add(new Weapon(str(context, R.string.ifrits_dagger), WeaponTypes.DAGGER, Elements.FIRE, 22, 101, 15, 0, 20, 2, R.drawable.dagger_ifrits_dagger, 400, 0, false, false, false, false));
        daggerList.add(new Weapon(str(context, R.string.dagger_of_sand), WeaponTypes.DAGGER, Elements.AIR, 32, 131, 13, 0, 20, 2, R.drawable.dagger_dagger_of_sand, 384, 0, false, false, false, false));
        daggerList.add(new Weapon(str(context, R.string.dark_dagger), WeaponTypes.DAGGER, Elements.DARKNESS, 36, 148, 13, 0, 25, 2, R.drawable.dagger_dark_dagger, 360, 0, false, false, false, false));
        daggerList.add(new Weapon(str(context, R.string.precious_skewer), WeaponTypes.DAGGER, Elements.NEUTRAL, 35, 161, 15, 0, 30, 3, R.drawable.dagger_precious_skewer, 360, 0, false, false, false, false));
        daggerList.add(new Weapon(str(context, R.string.dark_dagger_plus), WeaponTypes.DAGGER, Elements.DARKNESS, 40, 164, 13, 0, 25, 3, R.drawable.dagger_dark_dagger, 330, 0, false, false, false, false));
        daggerList.add(new Weapon(str(context, R.string.last_survivors_dagger), WeaponTypes.DAGGER, Elements.NEUTRAL, 36, 165, 15, 0, 20, 3, R.drawable.dagger_last_survivors_dagger, 300, 0, false, false, false, false));
        daggerList.add(new Weapon(str(context, R.string.precious_dual_blade), WeaponTypes.DAGGER, Elements.NEUTRAL, 37, 170, 15, 0, 12, 5, R.drawable.dagger_precious_dual_blade, 400, 1, false, true, false, false));
        daggerList.add(new Weapon(str(context, R.string.bunnyhop_dagger), WeaponTypes.DAGGER, Elements.NEUTRAL, 39, 179, 15, 0, 20, 18, R.drawable.dagger_bunnyhop_dagger, 550, 1, true, false, false, false));
        daggerList.add(new Weapon(str(context, R.string.gayan), WeaponTypes.DAGGER, Elements.EARTH, 42, 183, 14, 30, 27, 4, R.drawable.dagger_gayan, 360, 0, false, false, false, false));
        daggerList.add(new Weapon(str(context, R.string.ice_dagger), WeaponTypes.DAGGER, Elements.WATER, 40, 184, 15, 0, 15, 3, R.drawable.dagger_ice_dagger, 360, 1, true, false, false, true));
        daggerList.add(new Weapon(str(context, R.string.sapphire_pawns_dagger), WeaponTypes.DAGGER, Elements.NEUTRAL, 42, 193, 15, 0, 20, 0, R.drawable.dagger_sapphire_pawns_dagger, 500, 0, false, false, false, true));
        daggerList.add(new Weapon(str(context, R.string.venomous_dagger), WeaponTypes.DAGGER, Elements.NEUTRAL, 44, 202, 15, 0, 18, 2, R.drawable.dagger_venomous_dagger, 400, 1, true, false, true, false));
        daggerList.add(new Weapon(str(context, R.string.survivors_double_dagger), WeaponTypes.DAGGER, Elements.NEUTRAL, 44, 202, 15, 0, 15, 5, R.drawable.dagger_survivors_double_dagger, 400, 1, true, true, false, false));
        daggerList.add(new Weapon(str(context, R.string.undines_dagger), WeaponTypes.DAGGER, Elements.WATER, 50, 206, 13, 0, 25, 4, R.drawable.dagger_undines_dagger, 500, 0, false, false, true, false));
        daggerList.add(new Weapon(str(context, R.string.dragon_tooth_dagger), WeaponTypes.DAGGER, Elements.NEUTRAL, 45, 207, 15, -40, 25, 12, R.drawable.dagger_dragon_tooth_dagger, 360, 1, true, false, false, false));
        daggerList.add(new Weapon(str(context, R.string.dual_dragon_fang), WeaponTypes.DAGGER, Elements.NEUTRAL, 48, 220, 15, 0, 15, 5, R.drawable.dagger_dual_dragon_fang, 400, 1, true, true, false, false));
        daggerList.add(new Weapon(str(context, R.string.cthulhu_dagger), WeaponTypes.DAGGER, Elements.DARKNESS, 48, 220, 15, 0, 20, 3, R.drawable.dagger_cthulhu_dagger, 400, 2, true, false, true, false));
        daggerList.add(new Weapon(str(context, R.string.toxic_dual_dagger), WeaponTypes.DAGGER, Elements.NEUTRAL, 50, 230, 15, 0, 15, 5, R.drawable.dagger_toxic_dual_dagger, 500, 1, true, true, true, false));
        daggerList.add(new Weapon(str(context, R.string.abyssal_dual_blade), WeaponTypes.DAGGER, Elements.WATER, 50, 230, 15, 0, 15, 5, R.drawable.dagger_abyssal_dual_blade, 500, 1, true, true, true, false));
        daggerList.add(new Weapon(str(context, R.string.iron_dagger_plus), WeaponTypes.DAGGER, Elements.NEUTRAL, 50, 230, 15, -20, 25, 0, R.drawable.dagger_iron_dagger_plus, 440, 1, true, false, false, false));
        daggerList.add(new Weapon(str(context, R.string.malicious_quickblade), WeaponTypes.DAGGER, Elements.NEUTRAL, 52, 239, 15, 0, 20, 5, R.drawable.dagger_malicious_quickblade, 390, 1, true, false, true, false));
        daggerList.add(new Weapon(str(context, R.string.all_seeing_cleaver), WeaponTypes.DAGGER, Elements.NEUTRAL, 54, 248, 15, -15, 25, 3, R.drawable.dagger_all_seeing_cleaver, 360, 1, true, false, false, false));
        daggerList.add(new Weapon(str(context, R.string.ruby_pawns_edge), WeaponTypes.DAGGER, Elements.NEUTRAL, 58, 266, 15, -20, 25, 0, R.drawable.dagger_ruby_pawns_edge, 440, 0, false, true, true, false));
        daggerList.add(new Weapon(str(context, R.string.blood_swiftblade), WeaponTypes.DAGGER, Elements.FIRE, 61, 280, 15, 0, 25, 0, R.drawable.dagger_blood_swiftblade, 250, 2, true, true, false, false));
        daggerList.add(new Weapon(str(context, R.string.ifrits_shuriken), WeaponTypes.DAGGER, Elements.FIRE, 74, 340, 15, -20, 15, 3, R.drawable.shuriken_ifrits_shuriken, 340, 0, false, false, true, false));
        daggerList.add(new Weapon(str(context, R.string.undines_shuriken), WeaponTypes.DAGGER, Elements.WATER, 76, 349, 15, -20, 15, 3, R.drawable.shuriken_undines_shuriken, 360, 0, false, false, false, true));
        daggerList.add(new Weapon(str(context, R.string.gayan_shuriken), WeaponTypes.DAGGER, Elements.EARTH, 80, 368, 15, -10, 15, 3, R.drawable.shuriken_gayan_shuriken, 340, 0, false, false, false, false));
        daggerList.add(new Weapon(str(context, R.string.shooting_star_shuriken), WeaponTypes.DAGGER, Elements.LIGHT, 84, 386, 15, -20, 18, 0, R.drawable.shuriken_shooting_star_shuriken, 360, 1, true, false, false, false));

        // Hammers
        hammerList.add(new Weapon(str(context, R.string.bionic_hammer), WeaponTypes.HAMMER, Elements.NEUTRAL, 38, 65, 1, 35, 0, 6, R.drawable.hammer_bionic_hammer, 500, 0, false, true, false, false));
        hammerList.add(new Weapon(str(context, R.string.dark_mace), WeaponTypes.HAMMER, Elements.DARKNESS, 35, 127, 11, 50, 2, 1, R.drawable.mace_silver_dark_mace, 700, 0, false, true, false, false));
        hammerList.add(new Weapon(str(context, R.string.spider_crusher), WeaponTypes.HAMMER, Elements.EARTH, 47, 159, 10, 35, 0, 2, R.drawable.hammer_spider_crusher, 800, 0, false, true, false, false));
        hammerList.add(new Weapon(str(context, R.string.inquisidor), WeaponTypes.HAMMER, Elements.DARKNESS, 40, 164, 3, 50, 1, 1, R.drawable.hammer_inquisidor, 700, 0, false, true, false, false));
        hammerList.add(new Weapon(str(context, R.string.thunder_hammer), WeaponTypes.HAMMER, Elements.NEUTRAL, 70, 204, 8, 45, 0, 2, R.drawable.hammer_thunder_hammer, 800, 0, false, true, false, false));
        hammerList.add(new Weapon(str(context, R.string.liquid_hammer), WeaponTypes.HAMMER, Elements.WATER, 46, 211, 15, 65, 5, 1, R.drawable.hammer_liquid_hammer, 1050, 1, true, true, false, false));
        hammerList.add(new Weapon(str(context, R.string.toxic_mace), WeaponTypes.HAMMER, Elements.NEUTRAL, 46, 211, 15, 50, 2, 0, R.drawable.mace_toxic_mace, 600, 0, false, true, true, false));
        hammerList.add(new Weapon(str(context, R.string.wealthy_smasher), WeaponTypes.HAMMER, Elements.NEUTRAL, 46, 211, 15, 70, 0, 2, R.drawable.hammer_wealthy_smasher, 1050, 1, true, true, false, false));
        hammerList.add(new Weapon(str(context, R.string.wealthy_crusher), WeaponTypes.HAMMER, Elements.NEUTRAL, 46, 211, 15, 70, 2, 0, R.drawable.mace_wealthy_crusher, 1050, 2, true, true, false, false));
        hammerList.add(new Weapon(str(context, R.string.falcon_hammer), WeaponTypes.HAMMER, Elements.AIR, 45, 217, 2, 60, 9, 2, R.drawable.hammer_falcon_hammer, 1050, 1, true, true, false, false));
        hammerList.add(new Weapon(str(context, R.string.hammer_of_light), WeaponTypes.HAMMER, Elements.LIGHT, 48, 220, 15, 50, 3, 3, R.drawable.hammer_hammer_of_light, 1050, 1, true, true, false, false));
        hammerList.add(new Weapon(str(context, R.string.toxic_hammer), WeaponTypes.HAMMER, Elements.NEUTRAL, 48, 220, 15, 70, 0, 0, R.drawable.hammer_toxic_hammer, 750, 1, true, true, true, false));
        hammerList.add(new Weapon(str(context, R.string.volcano_hammer), WeaponTypes.HAMMER, Elements.FIRE, 47, 227, 2, 80, 0, 0, R.drawable.hammer_volcano_hammer, 1050, 1, true, true, false, false));
        hammerList.add(new Weapon(str(context, R.string.verdant_hammer), WeaponTypes.HAMMER, Elements.EARTH, 48, 232, 2, 80, 0, 3, R.drawable.hammer_verdant_hammer, 1050, 1, true, true, false, false));
        hammerList.add(new Weapon(str(context, R.string.smasher_of_decay), WeaponTypes.HAMMER, Elements.NEUTRAL, 52, 239, 15, 50, 0, 0, R.drawable.hammer_smasher_of_decay, 900, 0, false, true, false, false));
        hammerList.add(new Weapon(str(context, R.string.war_forged_smasher), WeaponTypes.HAMMER, Elements.FIRE, 56, 257, 15, 70, 0, 0, R.drawable.hammer_war_forged_smasher, 750, 1, true, true, false, false));
        hammerList.add(new Weapon(str(context, R.string.mojaras_hammer), WeaponTypes.HAMMER, Elements.DARKNESS, 55, 266, 2, 70, 2, 2, R.drawable.hammer_mojaras_hammer, 1050, 1, true, true, false, false));
        hammerList.add(new Weapon(str(context, R.string.enlightened_hammer), WeaponTypes.HAMMER, Elements.LIGHT, 61, 280, 15, 60, 0, 0, R.drawable.hammer_enlightened_hammer, 750, 2, true, true, false, false));
        hammerList.add(new Weapon(str(context, R.string.bone_hammer), WeaponTypes.HAMMER, Elements.NEUTRAL, 62, 285, 15, 70, 0, 2, R.drawable.hammer_bone_hammer, 1050, 1, true, true, false, false));
        hammerList.add(new Weapon(str(context, R.string.wit_of_ancient_power), WeaponTypes.HAMMER, Elements.NEUTRAL, 60, 290, 16, 80, 0, 2, R.drawable.hammer_wit_of_ancient_power, 1400, 1, true, true, false, false));

        // Staffs
        staffList.add(new Weapon(str(context, R.string.nature_staff), WeaponTypes.STAFF, Elements.EARTH, 8, 13, 1, 0, 0, 0, R.drawable.staff_nature_gadarasts_staff, 800, 0, false, false, false, false));
        staffList.add(new Weapon(str(context, R.string.fire_staff), WeaponTypes.STAFF, Elements.FIRE, 10, 17, 1, 0, 0, 0, R.drawable.staff_fire_staff, 800, 0, false, false, false, false));
        staffList.add(new Weapon(str(context, R.string.light_staff), WeaponTypes.STAFF, Elements.LIGHT, 12, 20, 1, 0, 1, 1, R.drawable.staff_light_staff, 800, 0, false, false, false, false));
        staffList.add(new Weapon(str(context, R.string.oxymos_staff), WeaponTypes.STAFF, Elements.LIGHT, 21, 96, 15, 0, 0, 2, R.drawable.staff_oxymos_staff, 600, 0, false, true, false, false));
        staffList.add(new Weapon(str(context, R.string.gadarasts_staff), WeaponTypes.STAFF, Elements.EARTH, 32, 108, 10, 30, 1, 2, R.drawable.staff_nature_gadarasts_staff, 700, 0, false, false, false, false));
        staffList.add(new Weapon(str(context, R.string.staff_of_darkness), WeaponTypes.STAFF, Elements.DARKNESS, 41, 149, 11, 0, 2, 2, R.drawable.staff_staff_of_darkness, 700, 0, false, false, false, false));
        staffList.add(new Weapon(str(context, R.string.firebane), WeaponTypes.STAFF, Elements.FIRE, 41, 149, 11, 0, 2, 2, R.drawable.staff_firebane, 700, 0, false, true, false, false));
        staffList.add(new Weapon(str(context, R.string.epic_fire_staff), WeaponTypes.STAFF, Elements.FIRE, 49, 178, 11, 0, 3, 1, R.drawable.staff_epic_fire_staff, 750, 0, false, false, false, false));
        staffList.add(new Weapon(str(context, R.string.necromorphicon), WeaponTypes.STAFF, Elements.DARKNESS, 39, 179, 15, -40, 0, 0, R.drawable.grimoire_necromorphicon, 550, 1, true, false, false, false));
        staffList.add(new Weapon(str(context, R.string.the_testament_of_ifrit), WeaponTypes.STAFF, Elements.FIRE, 39, 179, 15, 0, 8, 0, R.drawable.grimoire_the_testament_of_ifrit, 380, 4, true, false, false, false));
        staffList.add(new Weapon(str(context, R.string.the_arachnid_codex), WeaponTypes.STAFF, Elements.NEUTRAL, 42, 193, 15, -25, 4, 4, R.drawable.grimoire_the_arachnid_codex, 500, 2, true, false, true, false));
        staffList.add(new Weapon(str(context, R.string.compendium_of_trees), WeaponTypes.STAFF, Elements.EARTH, 43, 197, 15, 20, 3, 0, R.drawable.grimoire_compendium_of_trees, 550, 1, true, false, false, false));
        staffList.add(new Weapon(str(context, R.string.dragon_orb_staff), WeaponTypes.STAFF, Elements.FIRE, 48, 197, 13, 0, 1, 1, R.drawable.staff_dragon_orb_staff, 500, 0, false, true, false, false));
        staffList.add(new Weapon(str(context, R.string.the_oxymos_codex), WeaponTypes.STAFF, Elements.LIGHT, 44, 202, 15, -20, 10, 0, R.drawable.grimoire_the_oxymos_codex, 450, 1, true, false, false, false));
        staffList.add(new Weapon(str(context, R.string.the_abyssal_scrolls), WeaponTypes.STAFF, Elements.WATER, 48, 220, 15, 0, 3, 0, R.drawable.grimoire_the_abyssal_scrolls, 500, 3, true, false, false, false));
        staffList.add(new Weapon(str(context, R.string.the_word_of_the_wind), WeaponTypes.STAFF, Elements.AIR, 51, 234, 15, -20, 8, 0, R.drawable.grimoire_the_word_of_the_wind, 500, 2, true, false, false, false));
        staffList.add(new Weapon(str(context, R.string.the_daemon_codices), WeaponTypes.STAFF, Elements.DARKNESS, 54, 248, 15, -20, 0, 7, R.drawable.grimoire_the_daemon_codices, 400, 2, false, false, false, false));
        staffList.add(new Weapon(str(context, R.string.broom_staff), WeaponTypes.STAFF, Elements.EARTH, 60, 276, 15, 0, 0, 9, R.drawable.staff_broom_staff, 650, 1, true, true, false, false));
        staffList.add(new Weapon(str(context, R.string.icebane), WeaponTypes.STAFF, Elements.WATER, 62, 285, 15, 30, 4, 2, R.drawable.staff_icebane, 610, 1, true, true, false, true));
        staffList.add(new Weapon(str(context, R.string.nightfall), WeaponTypes.STAFF, Elements.DARKNESS, 62, 285, 15, 30, 2, 4, R.drawable.staff_nightfall, 610, 1, true, true, false, true));
        staffList.add(new Weapon(str(context, R.string.tome_of_the_sands), WeaponTypes.STAFF, Elements.AIR, 66, 303, 15, -35, 10, 0, R.drawable.grimoire_tome_of_the_sands, 400, 2, true, false, false, false));
        staffList.add(new Weapon(str(context, R.string.hippie_dragon_staff), WeaponTypes.STAFF, Elements.EARTH, 70, 322, 15, 40, 5, 3, R.drawable.staff_hippie_dragon_staff, 550, 0, false, true, false, false));
        staffList.add(new Weapon(str(context, R.string.dragonskull_staff), WeaponTypes.STAFF, Elements.FIRE, 72, 331, 15, 0, 5, 1, R.drawable.staff_dragonskull_staff, 650, 0, false, true, false, false));
        staffList.add(new Weapon(str(context, R.string.legacy_of_the_oracle), WeaponTypes.STAFF, Elements.EARTH, 72, 331, 15, 15, 3, 2, R.drawable.staff_legacy_of_the_oracle, 600, 1, true, true, false, false));
        staffList.add(new Weapon(str(context, R.string.royal_war_staff), WeaponTypes.STAFF, Elements.NEUTRAL, 72, 331, 15, 20, 3, 2, R.drawable.staff_royal_war_staff, 600, 0, false, true, false, false));
        staffList.add(new Weapon(str(context, R.string.hippie_dragon_staff_plus), WeaponTypes.STAFF, Elements.EARTH, 75, 345, 15, 30, 2, 2, R.drawable.staff_hippie_dragon_staff, 650, 0, false, true, false, false));
        staffList.add(new Weapon(str(context, R.string.seabane), WeaponTypes.STAFF, Elements.WATER, 75, 345, 15, 20, 4, 2, R.drawable.staff_seabane, 610, 1, true, true, false, false));
        staffList.add(new Weapon(str(context, R.string.golden_dragon_staff), WeaponTypes.STAFF, Elements.LIGHT, 76, 349, 15, 20, 3, 2, R.drawable.staff_golden_dragon_staff, 650, 0, false, true, false, false));
        staffList.add(new Weapon(str(context, R.string.cthulhu_staff), WeaponTypes.STAFF, Elements.DARKNESS, 77, 354, 15, 30, 0, 3, R.drawable.staff_cthulhu_staff, 590, 2, true, true, true, false));
        staffList.add(new Weapon(str(context, R.string.death_scythe), WeaponTypes.STAFF, Elements.DARKNESS, 80, 368, 15, 0, 4, 1, R.drawable.staff_death_scythe, 650, 0, false, true, false, false));
        staffList.add(new Weapon(str(context, R.string.water_staff), WeaponTypes.STAFF, Elements.WATER, 80, 368, 15, 0, 3, 3, R.drawable.staff_water_staff, 650, 0, false, true, false, false));
        staffList.add(new Weapon(str(context, R.string.death_scythe), WeaponTypes.STAFF, Elements.DARKNESS, 85, 391, 15, 0, 4, 3, R.drawable.staff_death_scythe, 450, 1, true, true, false, false));
        staffList.add(new Weapon(str(context, R.string.toxic_staff), WeaponTypes.STAFF, Elements.EARTH, 90, 414, 15, 0, 5, 2, R.drawable.staff_toxic_staff, 450, 0, false, true, true, false));
        staffList.add(new Weapon(str(context, R.string.dragonskull_staff_plus), WeaponTypes.STAFF, Elements.FIRE, 90, 414, 15, 0, 4, 2, R.drawable.staff_dragonskull_staff, 550, 1, true, true, false, false));
        staffList.add(new Weapon(str(context, R.string.golden_dragon_staff_plus), WeaponTypes.STAFF, Elements.LIGHT, 90, 414, 15, 20, 5, 3, R.drawable.staff_golden_dragon_staff, 650, 1, true, true, false, false));
        staffList.add(new Weapon(str(context, R.string.windbane), WeaponTypes.STAFF, Elements.AIR, 90, 414, 15, 0, 8, 2, R.drawable.staff_windbane, 600, 2, true, true, false, false));
        staffList.add(new Weapon(str(context, R.string.spider_staff), WeaponTypes.STAFF, Elements.DARKNESS, 90, 414, 15, 0, 4, 4, R.drawable.staff_spider_staff, 590, 1, true, true, true, false));
        staffList.add(new Weapon(str(context, R.string.dead_vulture_staff), WeaponTypes.STAFF, Elements.DARKNESS, 95, 437, 15, 0, 4, 1, R.drawable.staff_dead_vulture_staff, 650, 1, true, true, false, false));
        staffList.add(new Weapon(str(context, R.string.staff_of_the_wicked), WeaponTypes.STAFF, Elements.NEUTRAL, 110, 506, 15, 20, 3, 2, R.drawable.staff_staff_of_the_wicked, 400, 0, false, false, false, false));
        staffList.add(new Weapon(str(context, R.string.voidcaller_staff), WeaponTypes.STAFF, Elements.DARKNESS, 115, 529, 15, -30, 4, 0, R.drawable.staff_voidcaller_staff, 600, 1, false, false, false, false));
        staffList.add(new Weapon(str(context, R.string.ancient_stone_staff), WeaponTypes.STAFF, Elements.NEUTRAL, 120, 552, 15, 0, 0, 0, R.drawable.staff_ancient_stone_staff, 700, 0, false, false, false, false));

        // Spears
        spearList.add(new Weapon(str(context, R.string.obsidian_spear), WeaponTypes.SPEAR, Elements.NEUTRAL, 40, 164, 3, 20, 4, 3, R.drawable.spear_obsidian_spear, 750, 4, false, true, false, false));
        spearList.add(new Weapon(str(context, R.string.cthulhu_spear), WeaponTypes.SPEAR, Elements.DARKNESS, 42, 193, 15, 100, 0, 0, R.drawable.spear_cthulhu_spear, 750, 4, false, true, true, false));
        spearList.add(new Weapon(str(context, R.string.gayan_spear), WeaponTypes.SPEAR, Elements.EARTH, 53, 243, 2, 65, 3, 4, R.drawable.spear_gayan_spear, 750, 4, false, true, false, false));
        spearList.add(new Weapon(str(context, R.string.golden_piercer), WeaponTypes.SPEAR, Elements.NEUTRAL, 55, 253, 15, 20, 4, 3, R.drawable.spear_golden_piercer, 750, 4, false, true, false, false));
        spearList.add(new Weapon(str(context, R.string.yansahn), WeaponTypes.SPEAR, Elements.AIR, 57, 262, 2, 0, 10, 4, R.drawable.spear_yansahn, 750, 4, false, true, false, false));
        spearList.add(new Weapon(str(context, R.string.fire_pierce), WeaponTypes.SPEAR, Elements.FIRE, 58, 266, 2, 0, 5, 3, R.drawable.spear_fire_pierce, 750, 4, false, true, false, false));
        spearList.add(new Weapon(str(context, R.string.freyr), WeaponTypes.SPEAR, Elements.LIGHT, 58, 266, 2, 40, 6, 7, R.drawable.spear_freyr, 750, 4, false, true, false, false));
        spearList.add(new Weapon(str(context, R.string.poisoned_spear), WeaponTypes.SPEAR, Elements.EARTH, 58, 266, 15, 0, 10, 0, R.drawable.spear_poisoned_spear, 500, 4, true, true, true, false));
        spearList.add(new Weapon(str(context, R.string.last_survivors_spear), WeaponTypes.SPEAR, Elements.NEUTRAL, 61, 280, 15, 20, 2, 2, R.drawable.spear_last_survivors_spear, 750, 3, false, true, false, false));
        spearList.add(new Weapon(str(context, R.string.osun), WeaponTypes.SPEAR, Elements.WATER, 64, 294, 2, 20, 5, 4, R.drawable.spear_osun, 750, 4, false, true, false, false));
        spearList.add(new Weapon(str(context, R.string.gorgon_spear), WeaponTypes.SPEAR, Elements.NEUTRAL, 64, 294, 15, 0, 10, 0, R.drawable.spear_gorgon_spear, 600, 4, true, true, true, false));
        spearList.add(new Weapon(str(context, R.string.azatoth), WeaponTypes.SPEAR, Elements.DARKNESS, 67, 308, 2, 30, 5, 3, R.drawable.spear_azatoth, 750, 4, false, true, false, false));
        spearList.add(new Weapon(str(context, R.string.spider_spear), WeaponTypes.SPEAR, Elements.EARTH, 68, 312, 15, 25, 3, 12, R.drawable.spear_spider_spear, 650, 4, false, true, true, false));
        spearList.add(new Weapon(str(context, R.string.wicked_skewer), WeaponTypes.SPEAR, Elements.FIRE, 72, 331, 15, 0, 5, 3, R.drawable.spear_wicked_skewer, 450, 3, false, true, false, false));
        spearList.add(new Weapon(str(context, R.string.ruby_queens_spear), WeaponTypes.SPEAR, Elements.FIRE, 74, 340, 15, 0, 5, 3, R.drawable.spear_ruby_queens_spear, 650, 4, false, true, false, false));
        spearList.add(new Weapon(str(context, R.string.vindictive_piercer), WeaponTypes.SPEAR, Elements.AIR, 80, 368, 15, 0, 6, 2, R.drawable.spear_vindictive_piercer, 650, 5, false, true, false, false));
        spearList.add(new Weapon(str(context, R.string.onyx_queens_lance), WeaponTypes.SPEAR, Elements.WATER, 84, 386, 15, 0, 5, 0, R.drawable.spear_onyx_queens_lance, 650, 4, false, true, false, false));

        // Axes
        axeList.add(new Weapon(str(context, R.string.wooden_hawaiian), WeaponTypes.AXE, Elements.NEUTRAL, 10, 17, 1, 0, 0, 0, R.drawable.mace_wooden_hawaiian, 800, 0, false, false, false, false));
        axeList.add(new Weapon(str(context, R.string.silver_mace), WeaponTypes.AXE, Elements.NEUTRAL, 12, 20, 1, 35, 0, 0, R.drawable.mace_silver_dark_mace, 800, 0, false, true, false, false));
        axeList.add(new Weapon(str(context, R.string.silver_axe), WeaponTypes.AXE, Elements.NEUTRAL, 13, 22, 1, 35, 0, 0, R.drawable.axe_silver_fire_lightning_axe, 800, 0, false, false, false, false));
        axeList.add(new Weapon(str(context, R.string.club), WeaponTypes.AXE, Elements.NEUTRAL, 16, 27, 1, 30, 0, 0, R.drawable.mace_club, 800, 0, false, true, false, false));
        axeList.add(new Weapon(str(context, R.string.iron_mace), WeaponTypes.AXE, Elements.NEUTRAL, 16, 27, 1, 30, 0, 0, R.drawable.mace_iron_mace, 800, 0, false, true, false, false));
        axeList.add(new Weapon(str(context, R.string.insect_crusher), WeaponTypes.AXE, Elements.NEUTRAL, 16, 27, 1, 35, 0, 0, R.drawable.hammer_insect_crusher, 800, 0, false, true, false, false));
        axeList.add(new Weapon(str(context, R.string.wooden_hammer), WeaponTypes.AXE, Elements.EARTH, 17, 41, 6, 35, 0, 0, R.drawable.hammer_wooden_hammer, 800, 0, false, true, false, false));
        axeList.add(new Weapon(str(context, R.string.umbranian_cutter), WeaponTypes.AXE, Elements.NEUTRAL, 35, 60, 1, 30, 0, 0, R.drawable.axe_umbranian_flaming_cutter, 800, 0, false, true, false, false));
        axeList.add(new Weapon(str(context, R.string.bone_chopper), WeaponTypes.AXE, Elements.AIR, 22, 69, 9, 35, 6, 3, R.drawable.axe_bone_chopper, 450, 0, false, false, false, false));
        axeList.add(new Weapon(str(context, R.string.axe_of_fire), WeaponTypes.AXE, Elements.FIRE, 17, 78, 15, 30, 3, 0, R.drawable.axe_silver_fire_lightning_axe, 600, 0, false, false, false, false));
        axeList.add(new Weapon(str(context, R.string.warhammer), WeaponTypes.AXE, Elements.NEUTRAL, 28, 108, 12, 50, 0, 0, R.drawable.hammer_warhammer, 800, 0, false, true, false, false));
        axeList.add(new Weapon(str(context, R.string.flaming_cutter), WeaponTypes.AXE, Elements.FIRE, 24, 110, 15, 40, 4, 1, R.drawable.axe_umbranian_flaming_cutter, 600, 0, false, false, false, false));
        axeList.add(new Weapon(str(context, R.string.lightning_axe), WeaponTypes.AXE, Elements.LIGHT, 25, 115, 15, 0, 3, 2, R.drawable.axe_silver_fire_lightning_axe, 450, 1, true, true, false, false));
        axeList.add(new Weapon(str(context, R.string.spider_axe), WeaponTypes.AXE, Elements.FIRE, 40, 164, 3, 30, 3, 3, R.drawable.axe_spider_axe, 600, 0, false, true, true, false));
        axeList.add(new Weapon(str(context, R.string.fortunes_battleaxe), WeaponTypes.AXE, Elements.NEUTRAL, 48, 220, 15, 35, 0, 0, R.drawable.axe_fortunes_battleaxe, 800, 1, true, true, false, false));
        axeList.add(new Weapon(str(context, R.string.toxic_axe), WeaponTypes.AXE, Elements.NEUTRAL, 52, 239, 15, 40, 3, 2, R.drawable.axe_toxic_axe, 600, 1, true, true, true, false));
        axeList.add(new Weapon(str(context, R.string.eggscellent_axe), WeaponTypes.AXE, Elements.NEUTRAL, 52, 239, 15, 30, 3, 17, R.drawable.axe_eggscellent_axe, 500, 0, false, true, false, false));
        axeList.add(new Weapon(str(context, R.string.axe_of_rusted_gods), WeaponTypes.AXE, Elements.NEUTRAL, 53, 243, 15, 35, 0, 0, R.drawable.axe_axe_of_rusted_gods, 800, 0, false, true, false, false));
        axeList.add(new Weapon(str(context, R.string.bone_axe), WeaponTypes.AXE, Elements.NEUTRAL, 60, 276, 15, 20, 7, 3, R.drawable.axe_bone_axe, 380, 1, true, true, false, false));
        axeList.add(new Weapon(str(context, R.string.steel_axe), WeaponTypes.AXE, Elements.NEUTRAL, 70, 322, 15, 35, 0, 0, R.drawable.axe_steel_axe, 800, 2, true, true, false, false));
        axeList.add(new Weapon(str(context, R.string.ice_axe), WeaponTypes.AXE, Elements.NEUTRAL, 70, 322, 15, 30, 2, 5, R.drawable.axe_ice_axe, 450, 0, false, false, false, true));
        axeList.add(new Weapon(str(context, R.string.cthulhu_axe), WeaponTypes.AXE, Elements.DARKNESS, 74, 340, 15, 40, 4, 3, R.drawable.axe_cthulhu_axe, 600, 1, true, true, true, false));
        axeList.add(new Weapon(str(context, R.string.path_of_exile), WeaponTypes.AXE, Elements.FIRE, 74, 340, 15, 40, 4, 0, R.drawable.axe_path_of_exile, 750, 1, true, true, false, false));
        axeList.add(new Weapon(str(context, R.string.dawnlight), WeaponTypes.AXE, Elements.LIGHT, 75, 345, 15, 50, 2, 2, R.drawable.axe_dawnlight, 450, 1, true, true, false, false));
        axeList.add(new Weapon(str(context, R.string.stormcaller), WeaponTypes.AXE, Elements.WATER, 75, 345, 15, 30, 2, 3, R.drawable.axe_stormcaller, 600, 1, true, true, false, false));
        axeList.add(new Weapon(str(context, R.string.windpearl_axe), WeaponTypes.AXE, Elements.AIR, 75, 345, 15, 20, 8, 1, R.drawable.axe_windpearl_axe, 600, 1, true, true, false, false));
        axeList.add(new Weapon(str(context, R.string.path_of_exile_plus), WeaponTypes.AXE, Elements.FIRE, 82, 377, 15, 60, 7, 3, R.drawable.axe_path_of_exile, 550, 1, true, true, false, false));
        axeList.add(new Weapon(str(context, R.string.gorgon_axe), WeaponTypes.AXE, Elements.EARTH, 90, 414, 15, 40, 6, 1, R.drawable.axe_gorgon_axe, 600, 1, true, false, true, false));
        axeList.add(new Weapon(str(context, R.string.all_seeing_axe), WeaponTypes.AXE, Elements.DARKNESS, 98, 450, 15, 50, 3, 3, R.drawable.axe_all_seeing_axe, 600, 1, true, true, false, false));

        // Armors
        armorList.add(new Armor(str(context, R.string.cleric_vest), Elements.LIGHT, false, 8, 13, 1, 2, 2, 35, 0, 20, 20, 0, 0, 0, R.drawable.armor_cleric_vest));
        armorList.add(new Armor(str(context, R.string.nature_mage_vest), Elements.EARTH, false, 8, 13, 1, 0, 0, 30, 0, 20, 0, 0, 0, 0, R.drawable.armor_nature_mage_vest));
        armorList.add(new Armor(str(context, R.string.fire_mage_vest), Elements.FIRE, false, 8, 13, 1, 0, 0, 30, 0, 20, 0, 0, 0, 0, R.drawable.armor_fire_mage_vest));
        armorList.add(new Armor(str(context, R.string.druid_vest), Elements.EARTH, false, 15, 43, 8, 0, 3, 35, 0, 25, 25, 0, 0, 0, R.drawable.armor_druid_vest));
        armorList.add(new Armor(str(context, R.string.recruit_set), Elements.NEUTRAL, false, 6, 10, 1, 0, 0, 0, 10, 0, 15, 0, 0, 0, R.drawable.armor_recruit_soldier_set));
        armorList.add(new Armor(str(context, R.string.soldier_set), Elements.NEUTRAL, false, 12, 20, 1, 0, 0, 0, 20, 0, 20, 15, 0, 0, R.drawable.armor_recruit_soldier_set));
        armorList.add(new Armor(str(context, R.string.elite_soldier_set), Elements.NEUTRAL, false, 15, 25, 1, 3, 2, 0, 30, 0, 20, 20, 0, 0, R.drawable.armor_elite_soldier_set));
        armorList.add(new Armor(str(context, R.string.plague_fighter_suit), Elements.AIR, false, 14, 24, 1, 4, 3, 0, 0, 0, 20, 0, 0, 0, R.drawable.armor_plague_fighter_suit));
        armorList.add(new Armor(str(context, R.string.ranger_set), Elements.AIR, false, 19, 32, 1, 3, 2, 0, 30, 0, 30, 0, 0, 0, R.drawable.armor_ranger_umbranian_set));
        armorList.add(new Armor(str(context, R.string.elite_brass_set), Elements.NEUTRAL, false, 36, 61, 1, 2, 2, 0, 20, 0, 0, 25, 25, 0, R.drawable.armor_elite_brass_set));
        armorList.add(new Armor(str(context, R.string.brass_set), Elements.NEUTRAL, false, 30, 51, 1, 1, 1, 0, 15, 0, 0, 20, 20, 0, R.drawable.armor_brass_set));
        armorList.add(new Armor(str(context, R.string.obsidian_set), Elements.NEUTRAL, false, 42, 72, 1, 2, 2, 0, 25, 0, 0, 30, 30, 0, R.drawable.armor_obsidian_set));
        armorList.add(new Armor(str(context, R.string.jumpman_suit), Elements.AIR, false, 0, 0, 1, -20, 28, 0, 0, 0, 0, 0, 0, 0, R.drawable.armor_jumpman_suit));
        armorList.add(new Armor(str(context, R.string.warlock_vest), Elements.DARKNESS, false, 22, 90, 13, 4, 2, 50, 0, 30, 30, 0, 0, 0, R.drawable.armor_warlock_vest));
        armorList.add(new Armor(str(context, R.string.heros_set), Elements.AIR, false, 25, 54, 5, 6, 2, 0, 40, 0, 40, 0, 20, 0, R.drawable.armor_heros_set));
        armorList.add(new Armor(str(context, R.string.ifrits_disciple_robe), Elements.FIRE, false, 22, 74, 10, 3, 2, 40, 0, 35, 35, 35, 0, 0, R.drawable.armor_ifrits_disciple_robe));
        armorList.add(new Armor(str(context, R.string.elite_obsidian_set), Elements.NEUTRAL, false, 53, 91, 1, 3, 2, 0, 35, 0, 0, 35, 35, 0, R.drawable.armor_elite_obsidian_set));
        armorList.add(new Armor(str(context, R.string.umbranian_vest), Elements.AIR, false, 21, 36, 1, 5, 3, 30, 20, 0, 40, 0, 0, 0, R.drawable.armor_umbranian_tanker));
        armorList.add(new Armor(str(context, R.string.faldangs_vest), Elements.LIGHT, false, 22, 80, 11, 4, 1, 45, 0, 35, 0, 0, 0, 0, R.drawable.armor_faldangs_vest));
        armorList.add(new Armor(str(context, R.string.umbranian_tanker), Elements.NEUTRAL, false, 80, 195, 6, 3, 2, 0, 60, 0, 0, 60, 60, 0, R.drawable.armor_ranger_umbranian_set));
        armorList.add(new Armor(str(context, R.string.high_elf_robe), Elements.EARTH, false, 25, 79, 9, 3, 2, 40, 40, 40, 0, 0, 0, 40, R.drawable.armor_high_elf_robe));
        armorList.add(new Armor(str(context, R.string.antiheros_set), Elements.AIR, false, 27, 85, 9, 7, 3, 40, 60, 0, 60, 0, 0, 0, R.drawable.armor_antiheros_set));
        armorList.add(new Armor(str(context, R.string.monks_tunic), Elements.LIGHT, false, 24, 75, 9, 4, 2, 60, 0, 30, 0, 0, 30, 0, R.drawable.armor_monks_tunic));
        armorList.add(new Armor(str(context, R.string.crow_set), Elements.DARKNESS, false, 38, 110, 8, 6, 2, 80, 50, 0, 0, 0, 50, 0, R.drawable.armor_crow_set));
        armorList.add(new Armor(str(context, R.string.greenmoon_vest), Elements.EARTH, false, 27, 91, 10, 4, 3, 60, 0, 40, 0, 0, 40, 40, R.drawable.armor_greenmoon_vest));
        armorList.add(new Armor(str(context, R.string.dragon_vest), Elements.FIRE, false, 24, 81, 10, 5, 1, 60, 0, 40, 40, 40, 0, 0, R.drawable.armor_dragon_vest));
        armorList.add(new Armor(str(context, R.string.penumbra_suit), Elements.DARKNESS, false, 23, 94, 13, 5, 3, 70, 0, 70, 50, 0, 0, 0, R.drawable.armor_penumbra_suit));
        armorList.add(new Armor(str(context, R.string.improved_jumpman_suit), Elements.AIR, false, 10, 10, 1, 5, 28, 0, 0, 0, 0, 0, 0, 0, R.drawable.armor_jumpman_suit));
        armorList.add(new Armor(str(context, R.string.high_cleric_tunic), Elements.LIGHT, false, 20, 82, 13, 5, 2, 60, 0, 40, 0, 0, 0, 0, R.drawable.armor_high_cleric_tunic));
        armorList.add(new Armor(str(context, R.string.moonkeeper_set), Elements.EARTH, false, 36, 96, 7, 6, 4, 60, 0, 0, 40, 0, 40, 0, R.drawable.armor_moonkeeper_set));
        armorList.add(new Armor(str(context, R.string.bacoon_set), Elements.WATER, false, 34, 115, 10, 4, 3, 65, 50, 0, 0, 0, 60, 0, R.drawable.armor_bacoon_set));
        armorList.add(new Armor(str(context, R.string.deathdoctor_set), Elements.DARKNESS, false, 20, 48, 6, 4, 1, 20, 0, 20, 55, 0, 0, 0, R.drawable.armor_deathdoctor_set));
        armorList.add(new Armor(str(context, R.string.blue_wizard_suit), Elements.WATER, false, 30, 94, 9, 4, 2, 60, 0, 60, 0, 60, 0, 0, R.drawable.armor_blue_wizard_suit));
        armorList.add(new Armor(str(context, R.string.special_dragon_vest), Elements.FIRE, false, 180, 180, 1, 6, 4, 80, 70, 90, 70, 90, 0, 0, R.drawable.armor_dragon_vest));
        armorList.add(new Armor(str(context, R.string.steelblow_armor), Elements.AIR, false, 45, 142, 9, 8, 4, 60, 65, 0, 75, 0, 0, 0, R.drawable.armor_steelblow_armor));
        armorList.add(new Armor(str(context, R.string.special_crow_set), Elements.DARKNESS, false, 29, 119, 6, 6, 4, 80, 70, 0, 0, 60, 60, 0, R.drawable.armor_special_crow_set));
        armorList.add(new Armor(str(context, R.string.special_antiheros_set), Elements.AIR, false, 25, 103, 3, 8, 5, 60, 70, 0, 70, 0, 0, 0, R.drawable.armor_antiheros_set));
        armorList.add(new Armor(str(context, R.string.champion_set), Elements.NEUTRAL, false, 90, 154, 3, 4, 4, 70, 100, 0, 0, 0, 0, 120, R.drawable.armor_champion_set));
        armorList.add(new Armor(str(context, R.string.light_champion_set), Elements.LIGHT, false, 110, 110, 1, 4, 4, 50, 100, 0, 0, 100, 100, 100, R.drawable.armor_light_champion_set));
        armorList.add(new Armor(str(context, R.string.dark_lord_set), Elements.DARKNESS, false, 45, 120, 7, 6, 2, 130, 70, 0, 70, 0, 0, 50, R.drawable.armor_dark_lord_set));
        armorList.add(new Armor(str(context, R.string.gayan_set), Elements.EARTH, false, 80, 80, 1, 4, 3, 80, 0, 0, 80, 80, 0, 100, R.drawable.armor_gayan_set));
        armorList.add(new Armor(str(context, R.string.firestorm_armor), Elements.FIRE, true, 50, 122, 6, 6, 2, 120, 0, 0, 30, 60, 0, 50, R.drawable.armor_firestorm_armor));
        armorList.add(new Armor(str(context, R.string.bankers_coat), Elements.DARKNESS, false, 10, 26, 7, 4, 4, 40, 0, 0, 30, 0, 0, 50, R.drawable.armor_bankers_coat));
        armorList.add(new Armor(str(context, R.string.spider_exoskeleton), Elements.DARKNESS, false, 27, 111, 3, 6, 3, 100, 0, 0, 35, 100, 0, 0, R.drawable.armor_spider_exoskeleton));
        armorList.add(new Armor(str(context, R.string.penumbra_suit_plus), Elements.DARKNESS, false, 26, 125, 2, 6, 4, 140, 0, 50, 0, 0, 0, 60, R.drawable.armor_penumbra_suit));
        armorList.add(new Armor(str(context, R.string.bacoon_set_plus), Elements.WATER, false, 28, 135, 2, 5, 5, 75, 60, 0, 0, 0, 80, 60, R.drawable.armor_bacoon_set));
        armorList.add(new Armor(str(context, R.string.steelblow_armor_plus), Elements.AIR, false, 28, 135, 2, 9, 5, 65, 70, 0, 80, 0, 0, 0, R.drawable.armor_steelblow_armor));
        armorList.add(new Armor(str(context, R.string.light_spellmaster_suit), Elements.LIGHT, false, 100, 100, 1, 6, 3, 110, 80, 80, 0, 0, 0, 0, R.drawable.armor_light_spellmaster_suit));
        armorList.add(new Armor(str(context, R.string.time_patroller_suit), Elements.NEUTRAL, false, 60, 203, 10, 4, 4, 300, 0, 0, 0, 0, 0, 0, R.drawable.armor_time_patroller_suit));
        armorList.add(new Armor(str(context, R.string.jungle_master), Elements.EARTH, false, 50, 122, 6, 4, 5, 80, 0, 80, 0, 0, 80, 100, R.drawable.armor_jungle_master));
        armorList.add(new Armor(str(context, R.string.firestorm_armor_plus), Elements.FIRE, true, 28, 135, 2, 8, 3, 80, 80, 0, 50, 70, 0, 70, R.drawable.armor_firestorm_armor));
        armorList.add(new Armor(str(context, R.string.fire_moonkeeper_set), Elements.FIRE, true, 35, 161, 15, 6, 3, 100, 0, 110, 110, 0, 0, 110, R.drawable.armor_fire_moonkeeper_set));
        armorList.add(new Armor(str(context, R.string.heros_set), Elements.AIR, false, 32, 147, 15, 15, 4, 70, 100, 0, 0, 0, 100, 100, R.drawable.armor_heros_set));
        armorList.add(new Armor(str(context, R.string.bankers_coat), Elements.DARKNESS, false, 32, 147, 15, 5, 4, 60, 0, 0, 200, 0, 0, 0, R.drawable.armor_bankers_coat));
        armorList.add(new Armor(str(context, R.string.jungle_assassin_suit), Elements.EARTH, false, 25, 79, 9, 4, 4, 45, 0, 35, 35, 0, 40, 0, R.drawable.armor_jungle_assassin_suit));
        armorList.add(new Armor(str(context, R.string.elite_assassin_suit), Elements.DARKNESS, false, 32, 78, 6, 5, 3, 60, 60, 0, 60, 60, 0, 60, R.drawable.armor_elite_assassin_suit));
        armorList.add(new Armor(str(context, R.string.liquid_assassin_suit), Elements.WATER, false, 34, 107, 9, 6, 3, 60, 60, 0, 60, 0, 60, 60, R.drawable.armor_liquid_assassin_suit));
        armorList.add(new Armor(str(context, R.string.witch_dress), Elements.EARTH, false, 16, 73, 15, 2, 7, 120, 0, 80, 80, 0, 0, 0, R.drawable.armor_witch_dress));
        armorList.add(new Armor(str(context, R.string.purple_witch_suit), Elements.DARKNESS, false, 22, 101, 15, 3, 3, 50, 0, 30, 0, 0, 0, 0, R.drawable.armor_purple_witch_suit));
        armorList.add(new Armor(str(context, R.string.green_witch_suit), Elements.EARTH, false, 16, 73, 15, 3, 3, 40, 0, 40, 0, 0, 0, 0, R.drawable.armor_green_witch_suit));
        armorList.add(new Armor(str(context, R.string.swamp_witch_suit), Elements.NEUTRAL, false, 34, 115, 10, 4, 4, 120, 140, 140, 80, 0, 0, 0, R.drawable.armor_swamp_witch_suit));
        armorList.add(new Armor(str(context, R.string.forest_witch_suit), Elements.EARTH, false, 14, 64, 15, 3, 4, 60, 0, 60, 0, 0, 40, 0, R.drawable.armor_forest_witch_suit));
        armorList.add(new Armor(str(context, R.string.black_witch_suit), Elements.DARKNESS, false, 19, 87, 15, 4, 2, 70, 0, 75, 0, 0, 0, 60, R.drawable.armor_black_witch_suit));
        armorList.add(new Armor(str(context, R.string.wind_witch_suit), Elements.AIR, false, 28, 128, 15, 6, 4, 150, 110, 0, 140, 0, 0, 140, R.drawable.armor_wind_witch_suit));
        armorList.add(new Armor(str(context, R.string.arcane_mage_suit), Elements.NEUTRAL, true, 30, 101, 10, 5, 3, 110, 0, 120, 80, 0, 80, 100, R.drawable.armor_arcane_mage_suit));
        armorList.add(new Armor(str(context, R.string.swamp_ranger_suit), Elements.NEUTRAL, true, 40, 136, 10, 5, 3, 70, 100, 0, 100, 130, 0, 130, R.drawable.armor_swamp_ranger_suit));
        armorList.add(new Armor(str(context, R.string.desert_rogue_suit), Elements.NEUTRAL, true, 50, 170, 10, 6, 3, 70, 0, 0, 130, 130, 0, 160, R.drawable.armor_desert_rogue_suit));
        armorList.add(new Armor(str(context, R.string.iron_widow), Elements.NEUTRAL, true, 56, 190, 10, 0, 0, 70, 140, 0, 0, 160, 140, 160, R.drawable.armor_iron_widow));
        armorList.add(new Armor(str(context, R.string.bunny_suit), Elements.NEUTRAL, false, 15, 15, 1, 5, 28, 0, 0, 0, 0, 0, 0, 0, R.drawable.armor_bunny_suit));
        armorList.add(new Armor(str(context, R.string.warden_of_demons), Elements.DARKNESS, false, 52, 239, 15, 0, -1, 80, 140, 0, 0, 140, 140, 0, R.drawable.armor_warden_of_demons));
        armorList.add(new Armor(str(context, R.string.unholy_storm), Elements.WATER, false, 42, 193, 15, 6, 4, 150, 0, 80, 80, 0, 0, 80, R.drawable.armor_unholy_storm));
        armorList.add(new Armor(str(context, R.string.tunic_of_the_relentless), Elements.WATER, true, 38, 174, 15, 6, 4, 155, 70, 80, 0, 0, 0, 90, R.drawable.armor_tunic_of_the_relentless));
        armorList.add(new Armor(str(context, R.string.destroyer_of_the_corrupted), Elements.LIGHT, false, 52, 239, 15, 0, -1, 80, 100, 0, 0, 140, 170, 0, R.drawable.armor_destroyer_of_the_corrupted));
        armorList.add(new Armor(str(context, R.string.interrogator), Elements.WATER, false, 51, 234, 15, 0, 0, 110, 0, 0, 0, 140, 140, 150, R.drawable.armor_interrogator));
        armorList.add(new Armor(str(context, R.string.protector_of_the_oracle), Elements.EARTH, false, 51, 234, 15, -1, 0, 120, 0, 90, 0, 0, 160, 90, R.drawable.armor_protector_of_the_oracle));
        armorList.add(new Armor(str(context, R.string.death_stalker), Elements.DARKNESS, false, 26, 119, 15, 2, 0, 160, 0, 110, 130, 0, 0, 150, R.drawable.armor_death_stalker));
        armorList.add(new Armor(str(context, R.string.tunic_of_endless_justice), Elements.LIGHT, false, 24, 110, 15, 5, 3, 180, 70, 130, 0, 0, 0, 70, R.drawable.armor_tunic_of_endless_justice));
        armorList.add(new Armor(str(context, R.string.dark_lord_set), Elements.DARKNESS, false, 45, 131, 8, 6, 4, 130, 80, 0, 80, 0, 0, 80, R.drawable.armor_dark_lord_set));
        armorList.add(new Armor(str(context, R.string.cataclysmic_plate), Elements.FIRE, false, 56, 257, 15, -1, -1, 55, 140, 0, 0, 170, 220, 0, R.drawable.armor_cataclysmic_plate));
        armorList.add(new Armor(str(context, R.string.tunic_of_frozen_voices), Elements.WATER, true, 30, 138, 15, 0, 0, 170, 0, 120, 130, 0, 0, 150, R.drawable.armor_tunic_of_frozen_voices));
        armorList.add(new Armor(str(context, R.string.robe_of_distant_visions), Elements.EARTH, false, 29, 133, 15, 4, 3, 170, 0, 130, 0, 0, 0, 160, R.drawable.armor_robe_of_distant_visions));
        armorList.add(new Armor(str(context, R.string.tunic_of_distant_ancestors), Elements.EARTH, false, 36, 165, 15, 3, 2, 130, 0, 0, 170, 160, 0, 0, R.drawable.armor_tunic_of_distant_ancestors));
        armorList.add(new Armor(str(context, R.string.vanquisher), Elements.AIR, false, 55, 253, 15, 0, 0, 80, 170, 0, 0, 0, 0, 170, R.drawable.armor_vanquisher));
        armorList.add(new Armor(str(context, R.string.vest_of_phantoms_keeper), Elements.DARKNESS, false, 30, 138, 15, 4, 2, 100, 120, 0, 120, 0, 0, 0, R.drawable.armor_vest_of_phantoms_keeper));
        armorList.add(new Armor(str(context, R.string.robe_of_imminent_fires), Elements.FIRE, false, 35, 161, 15, 3, 0, 140, 0, 110, 0, 160, 0, 130, R.drawable.armor_robe_of_imminent_fires));
        armorList.add(new Armor(str(context, R.string.winter_witch_armor), Elements.WATER, true, 30, 101, 10, 3, 2, 80, 100, 100, 0, 0, 0, 0, R.drawable.armor_winter_witch_armor));
        armorList.add(new Armor(str(context, R.string.tubeman_suit), Elements.AIR, false, 10, 10, 1, 5, 28, 0, 0, 0, 0, 0, 0, 0, R.drawable.armor_tubeman_suit));
        armorList.add(new Armor(str(context, R.string.twitch_suit), Elements.AIR, false, 10, 10, 1, 5, 28, 0, 0, 0, 0, 0, 0, 0, R.drawable.armor_twitch_suit));
        armorList.add(new Armor(str(context, R.string.easterminator), Elements.NEUTRAL, false, 40, 184, 15, 5, 18, 40, 50, 0, 50, 0, 50, 0, R.drawable.armor_easterminator));
        armorList.add(new Armor(str(context, R.string.kings_spectre_tunic), Elements.NEUTRAL, false, 28, 95, 10, 4, 4, 400, 0, 0, 0, 0, 0, 0, R.drawable.armor_kings_spectre_tunic));
        armorList.add(new Armor(str(context, R.string.vest_of_twisted_illusions), Elements.DARKNESS, true, 30, 138, 15, 3, 0, 70, 0, 0, 0, 0, 0, 240, R.drawable.armor_vest_of_twisted_illusions));
        armorList.add(new Armor(str(context, R.string.cthulhu_set), Elements.NEUTRAL, false, 32, 147, 15, 2, 3, 130, 100, 100, 100, 100, 100, 100, R.drawable.armor_cthulhu_set));
        armorList.add(new Armor(str(context, R.string.barrenlands_banditin), Elements.NEUTRAL, false, 34, 156, 15, 2, 3, 70, 0, 80, 200, 120, 0, 0, R.drawable.armor_barrenlands_banditin));
        armorList.add(new Armor(str(context, R.string.tunic_of_ending_nights), Elements.NEUTRAL, true, 21, 96, 15, 3, 2, 150, 0, 140, 140, 0, 0, 0, R.drawable.armor_tunic_of_ending_nights));
        armorList.add(new Armor(str(context, R.string.santa_claus), Elements.LIGHT, true, 30, 30, 1, 8, 20, 0, 0, 0, 0, 0, 0, 0, R.drawable.armor_santa_claus));
        armorList.add(new Armor(str(context, R.string.tunic_of_twisted_illusions), Elements.EARTH, false, 28, 128, 15, 4, 8, 100, 0, 80, 100, 0, 0, 80, R.drawable.armor_tunic_of_twisted_illusions));
        armorList.add(new Armor(str(context, R.string.vest_of_blessed_glory), Elements.LIGHT, false, 36, 165, 15, 3, 2, 105, 170, 0, 100, 0, 130, 160, R.drawable.armor_vest_of_blessed_glory));
        armorList.add(new Armor(str(context, R.string.dancers_raiment), Elements.AIR, false, 10, 10, 1, 5, 28, 0, 0, 0, 0, 0, 0, 0, R.drawable.armor_dancers_raiment_tiktok));
        armorList.add(new Armor(str(context, R.string.barrenlands_bandit), Elements.NEUTRAL, false, 34, 156, 15, 2, 3, 70, 180, 0, 130, 0, 150, 0, R.drawable.armor_barrenlands_bandit));
        armorList.add(new Armor(str(context, R.string.robe_of_eternal_fire), Elements.FIRE, false, 27, 124, 15, 4, 3, 180, 120, 0, 0, 50, 0, 120, R.drawable.armor_robe_of_eternal_fire));
        armorList.add(new Armor(str(context, R.string.greenfang_ensemble), Elements.DARKNESS, false, 48, 220, 15, 6, 4, 100, 0, 0, 135, 0, 135, 0, R.drawable.armor_greenfang_ensemble));
        armorList.add(new Armor(str(context, R.string.enchanted_nutcracker), Elements.NEUTRAL, false, 30, 138, 15, 2, 4, 100, 120, 120, 0, 0, 0, 0, R.drawable.armor_enchanted_nutcracker));
        armorList.add(new Armor(str(context, R.string.tunic_of_hellish_illusions), Elements.DARKNESS, false, 20, 92, 15, 4, 8, 150, 0, 0, 0, 80, 100, 80, R.drawable.armor_tunic_of_hellish_illusions));
        armorList.add(new Armor(str(context, R.string.scarlet_shadowweaver), Elements.DARKNESS, false, 30, 138, 15, 4, 6, 130, 0, 135, 135, 0, 0, 0, R.drawable.armor_scarlet_shadowweaver));
        armorList.add(new Armor(str(context, R.string.storm), Elements.AIR, false, 28, 128, 15, 7, 4, 140, 0, 170, 0, 170, 0, 0, R.drawable.armor_storm));
        armorList.add(new Armor(str(context, R.string.gatekeepers_bionic_arm), Elements.NEUTRAL, false, 10, 46, 15, 6, 6, 0, 30, 0, 20, 30, 30, 0, R.drawable.armor_gatekeepers_bionic_arm));
        armorList.add(new Armor(str(context, R.string.innkeepers_costume), Elements.NEUTRAL, false, 46, 211, 15, 0, 30, 0, 0, 0, 0, 0, 0, 0, R.drawable.armor_innkeepers_costume));
        armorList.add(new Armor(str(context, R.string.vest_of_ominous_comrades), Elements.NEUTRAL, false, 26, 119, 15, 8, 0, 100, 100, 0, 0, 100, 100, 0, R.drawable.armor_vest_of_ominous_comrades));
        armorList.add(new Armor(str(context, R.string.vest_of_ominous_jesters), Elements.NEUTRAL, false, 26, 119, 15, 0, 12, 100, 0, 100, 100, 0, 0, 100, R.drawable.armor_vest_of_ominous_jesters));

        // Rings
        ringList.add(new Ring(str(context, R.string.ring_of_agility), Elements.NEUTRAL, 0, 0, 2, 2, 0, 20, 0, 0, 0, 0, 0, R.drawable.ring_ring_of_agility));
        ringList.add(new Ring(str(context, R.string.shaman_ring), Elements.NEUTRAL, 0, 0, 2, 2, 20, 0, 0, 0, 0, 0, 0, R.drawable.ring_shaman_narya_ring));
        ringList.add(new Ring(str(context, R.string.narya), Elements.FIRE, 0, 0, 2, 0, 20, 0, 0, 0, 20, 0, 0, R.drawable.ring_shaman_narya_ring));
        ringList.add(new Ring(str(context, R.string.nazguh_ring), Elements.DARKNESS, 0, 0, 0, 0, 20, 0, 20, 0, 0, 0, 0, R.drawable.ring_nazguh_ring));
        ringList.add(new Ring(str(context, R.string.ring_of_protection), Elements.EARTH, 14, 0, 2, 2, 15, 0, 10, 0, 0, 10, 0, R.drawable.ring_ring_of_protection));
        ringList.add(new Ring(str(context, R.string.cleric_ring), Elements.LIGHT, 0, 0, 1, 1, 20, 0, 20, 0, 0, 0, 0, R.drawable.ring_cleric_ring));
        ringList.add(new Ring(str(context, R.string.supersonic_ring), Elements.NEUTRAL, 0, -90, 70, 0, -90, 0, 0, 0, 0, 0, 0, R.drawable.ring_supersonic_ring));
        ringList.add(new Ring(str(context, R.string.swordsmans_ring), Elements.AIR, 0, 0, 5, 2, 0, 50, 0, 0, 0, 0, 0, R.drawable.ring_swordsmans_ring));
        ringList.add(new Ring(str(context, R.string.dragon_eye_ring), Elements.EARTH, 36, 0, 4, 2, 60, 0, 0, 0, 0, 50, 70, R.drawable.ring_dragon_eye_ring));
        ringList.add(new Ring(str(context, R.string.spellmasters_ring), Elements.FIRE, 0, 0, 4, 2, 70, 0, 60, 0, 40, 0, 0, R.drawable.ring_spellmasters_ring));
        ringList.add(new Ring(str(context, R.string.warlocks_ring), Elements.DARKNESS, 13, 0, 4, 2, 50, 0, 35, 35, 0, 0, 0, R.drawable.ring_warlock_ring));
        ringList.add(new Ring(str(context, R.string.nenya), Elements.WATER, 0, 0, 4, 2, 50, 0, 0, 40, 0, 0, 50, R.drawable.ring_nenya));
        ringList.add(new Ring(str(context, R.string.white_pearl_ring), Elements.LIGHT, 30, 0, 4, 3, 60, 0, 70, 0, 0, 0, 0, R.drawable.ring_white_pearl_ring));
        ringList.add(new Ring(str(context, R.string.steelblow_ring), Elements.AIR, 20, 0, 12, 3, 40, 50, 0, 30, 50, 0, 0, R.drawable.ring_steelblow_ring));
        ringList.add(new Ring(str(context, R.string.dragon_orb_ring), Elements.FIRE, 20, 0, 5, 2, 60, 0, 0, 0, 60, 0, 60, R.drawable.ring_dragon_orb_ring));
        ringList.add(new Ring(str(context, R.string.witchdoctor_ring), Elements.DARKNESS, 30, 0, 4, 2, 60, 0, 0, 50, 0, 50, 0, R.drawable.ring_witchdoctor_ring));
        ringList.add(new Ring(str(context, R.string.ring_of_light), Elements.LIGHT, 40, 0, 4, 4, 60, 50, 0, 50, 0, 50, 0, R.drawable.ring_ring_of_light));
        ringList.add(new Ring(str(context, R.string.falcon_ring), Elements.AIR, 5, 0, 8, 3, 80, 100, 0, 100, 0, 100, 0, R.drawable.ring_falcon_ring));
        ringList.add(new Ring(str(context, R.string.cursed_amethyst_ring), Elements.DARKNESS, 5, -40, 4, 3, 120, 0, 140, 0, 0, 0, 0, R.drawable.ring_cursed_amethyst_ring));
        ringList.add(new Ring(str(context, R.string.verdant_ring), Elements.EARTH, 16, 0, 4, 3, 70, 0, 70, 0, 0, 70, 0, R.drawable.ring_verdant_ring));
        ringList.add(new Ring(str(context, R.string.volcano_ring), Elements.FIRE, 20, 0, 3, 2, 75, 65, 65, 75, 0, 0, 0, R.drawable.ring_volcano_ring));
        ringList.add(new Ring(str(context, R.string.sea_wave_ring), Elements.WATER, 0, 0, 5, 3, 70, 60, 70, 0, 0, 70, 0, R.drawable.ring_sea_wave_ring));
        ringList.add(new Ring(str(context, R.string.dragon_fang_ring), Elements.NEUTRAL, 0, 0, 4, 4, 60, 70, 0, 0, 70, 70, 0, R.drawable.ring_dragon_fang_ring));
        ringList.add(new Ring(str(context, R.string.all_seeing_ring), Elements.DARKNESS, 20, 0, 4, 2, 60, 60, 60, 0, 70, 0, 0, R.drawable.ring_all_seeing_ring));
        ringList.add(new Ring(str(context, R.string.blue_ring), Elements.NEUTRAL, 0, 0, 4, 2, 60, 0, 70, 70, 0, 0, 70, R.drawable.ring_blue_ring));
        ringList.add(new Ring(str(context, R.string.cait), Elements.NEUTRAL, 30, 0, 6, 4, 80, 0, 80, 80, 0, 0, 0, R.drawable.ring_cait));
        ringList.add(new Ring(str(context, R.string.cuteulhu), Elements.NEUTRAL, 40, 0, 4, 3, 100, 0, 90, 0, 90, 90, 0, R.drawable.ring_cuteulhu));
        ringList.add(new Ring(str(context, R.string.spektator), Elements.NEUTRAL, 30, 0, 4, 3, 110, 80, 80, 80, 0, 0, 80, R.drawable.ring_spektator));
        ringList.add(new Ring(str(context, R.string.bunny_ring), Elements.NEUTRAL, 5, 0, 0, 10, 70, 0, 70, 60, 0, 0, 0, R.drawable.ring_bunny_ring));
        ringList.add(new Ring(str(context, R.string.whisper_of_fire), Elements.FIRE, 40, 0, 5, 3, 100, 90, 90, 0, 90, 0, 0, R.drawable.ring_whisper_of_fire));
        ringList.add(new Ring(str(context, R.string.creepy_crawler), Elements.NEUTRAL, 40, 0, 3, 3, 90, 40, 40, 40, 40, 40, 40, R.drawable.ring_creepy_crawler));
        ringList.add(new Ring(str(context, R.string.whisper_of_death), Elements.DARKNESS, 40, 0, 5, 3, 100, 0, 90, 90, 0, 90, 0, R.drawable.ring_whisper_of_death));
        ringList.add(new Ring(str(context, R.string.vina), Elements.EARTH, 50, 0, 2, 2, 100, 100, 100, 0, 0, 0, 0, R.drawable.ring_vina));
        ringList.add(new Ring(str(context, R.string.ancient_warden), Elements.WATER, 8, 0, 4, 3, 80, 100, 100, 0, 0, 140, 0, R.drawable.ring_ancient_warden));
        ringList.add(new Ring(str(context, R.string.magic_cog), Elements.NEUTRAL, 40, 0, 5, 3, 210, 0, 0, 0, 0, 0, 0, R.drawable.ring_magic_cog));
        ringList.add(new Ring(str(context, R.string.vindicator_guardian), Elements.AIR, 40, 0, 5, 4, 100, 90, 0, 100, 0, 0, 110, R.drawable.ring_vindicator_guardian));
        ringList.add(new Ring(str(context, R.string.whisper_of_light), Elements.LIGHT, 40, 0, 5, 3, 100, 90, 90, 0, 0, 120, 0, R.drawable.ring_whisper_of_light));
        ringList.add(new Ring(str(context, R.string.eastercreep), Elements.NEUTRAL, 5, 0, 0, 10, 60, 60, 0, 0, 0, 70, 0, R.drawable.ring_eastercreep));
        ringList.add(new Ring(str(context, R.string.ghostwalker), Elements.NEUTRAL, 40, 150, -2, 0, 40, 0, 0, 0, 0, 0, 0, R.drawable.ring_ghostwalker));
        ringList.add(new Ring(str(context, R.string.trickytreat), Elements.NEUTRAL, 20, 0, 3, 3, 30, 20, 20, 20, 20, 20, 20, R.drawable.ring_trickytreat));
        ringList.add(new Ring(str(context, R.string.jellybunny), Elements.NEUTRAL, 15, 0, 0, 10, 60, 0, 60, 70, 0, 0, 60, R.drawable.ring_jellybunny));
        ringList.add(new Ring(str(context, R.string.phoenix), Elements.FIRE, 40, 0, 2, 2, 100, 0, 0, 90, 0, 130, 90, R.drawable.ring_phoenix));
        ringList.add(new Ring(str(context, R.string.golden_guardian), Elements.NEUTRAL, 30, 0, 0, 0, 100, 0, 0, 0, 0, 130, 100, R.drawable.ring_golden_guardian));
        ringList.add(new Ring(str(context, R.string.pirouette_pointe), Elements.NEUTRAL, 10, 0, 5, 7, 40, 0, 0, 0, 0, 0, 0, R.drawable.ring_pirouette_pointe));
        ringList.add(new Ring(str(context, R.string.nightshade), Elements.NEUTRAL, 0, 0, 7, 9, 220, 0, 0, 0, 0, 0, 0, R.drawable.ring_nightshade));

        // Classes
        classList.add(new CharacterClass(ClassNames.RANGER, 0, 0, 35, 0, 0, 25, 0, 0, 0, 5, R.drawable.class_ranger));
        classList.add(new CharacterClass(ClassNames.PRIEST, 0, 0, 0, -31, 0, 0, 0, 0, 3, 4, R.drawable.class_priest));
        classList.add(new CharacterClass(ClassNames.WARLOCK, 0, 0, 25, 19, 0, 19, 0, 0, 4, 0, R.drawable.class_warlock));
        classList.add(new CharacterClass(ClassNames.BLACK_MAGE, 0, 0, 0, 19, -31, 0, 0, 0, 4, 2, R.drawable.class_black_mage));
        classList.add(new CharacterClass(ClassNames.ROGUE, 0, 0, -10, 50, -31, -31, 0, 0, 6, 5, R.drawable.class_rogue));
        classList.add(new CharacterClass(ClassNames.THIEF, 0, 0, 19, 39, 19, 0, 0, 0, 6, 7, R.drawable.class_thief));
        classList.add(new CharacterClass(ClassNames.WARRIOR, 0, 0, 30, 0, 30, 30, 0, 0, 0, 0, R.drawable.class_warrior));
        classList.add(new CharacterClass(ClassNames.MAGE, 0, 0, 0, 0, -31, 19, 0, 0, 2, 4, R.drawable.class_mage));
        classList.add(new CharacterClass(ClassNames.DRUID, 0, 0, 0, 0, 0, 0, 0, 0, 3, 6, R.drawable.class_druid));
        classList.add(new CharacterClass(ClassNames.PALADIN, 0, 0, 19, 0, 19, 19, 0, 0, 0, 0, R.drawable.class_paladin));
        classList.add(new CharacterClass(ClassNames.HIGH_MAGE, 0, 0, 19, 0, -31, 0, 0, 0, 6, 4, R.drawable.class_high_mage));
        classList.add(new CharacterClass(ClassNames.ELITE_WARRIOR, 0, 0, 35, 0, 35, 35, 0, 0, 0, 5, R.drawable.class_elite_warrior));
        classList.add(new CharacterClass(ClassNames.WITCHDOCTOR, 0, 0, 0, 25, 0, 0, 0, 0, 5, 6, R.drawable.class_witchdoctor));

        // Enemies
        enemyList.add(new Enemy(str(context, R.string.enemy_spider), 9, 18, 0, 0, 2.8, 21.5, "waypoints", "stoneThrower", R.drawable.enemy_spider));
        enemyList.add(new Enemy(str(context, R.string.enemy_zombie_noob_knife_guard), 13, 18, 0, 2, 5.0, 34.0, "waypoints", "knifeThrower", R.drawable.enemy_zombie));
        enemyList.add(new Enemy(str(context, R.string.enemy_zombie_guard), 14, 24, 0, 0, 6.0, 28.0, "waypoints", "stoneThrower", R.drawable.enemy_zombie));
        enemyList.add(new Enemy(str(context, R.string.enemy_armored_enraged_skeleton), 15, 19, 0, 0, 5.62, 31.0, "waypoints", "knifeThrower", R.drawable.enemy_jumping_fire_skeleton));
        enemyList.add(new Enemy(str(context, R.string.enemy_spider_b_weak), 15, 22, 0, 0, 3.2, 24.5, "waypoints", "stoneThrower", R.drawable.enemy_spider));
        enemyList.add(new Enemy(str(context, R.string.enemy_dark_ghost), 20, 25, 0, 0, 3.0, 16.5, "waypoints", "stoneThrower", R.drawable.enemy_dark_ghost));
        enemyList.add(new Enemy(str(context, R.string.enemy_zombie_knife_guard), 20, 15, 0, 2, 5.0, 34.0, "waypoints", "knifeThrower", R.drawable.enemy_zombie));
        enemyList.add(new Enemy(str(context, R.string.enemy_zombie_elite_guard), 26, 24, 0, 0, 8.0, 28.0, "waypoints", "stoneThrower", R.drawable.enemy_zombie));
        enemyList.add(new Enemy(str(context, R.string.enemy_beetle_anubis), 30, 22, 0, 0, 4.2, 24.5, "waypoints", "stoneThrower", R.drawable.enemy_beetle_anubis));
        enemyList.add(new Enemy(str(context, R.string.enemy_beetle_anubis_red), 30, 22, 0, 0, 4.2, 24.5, "waypoints", "stoneThrower", R.drawable.enemy_beetle_anubis_red));
        enemyList.add(new Enemy(str(context, R.string.enemy_spider_b), 30, 22, 0, 0, 3.2, 24.5, "waypoints", "stoneThrower", R.drawable.enemy_spider));
        enemyList.add(new Enemy(str(context, R.string.enemy_xmas_duck), 30, 22, 0, 0, 9.0, 24.5, "waypoints", "stoneThrower", R.drawable.enemy_xmas_duck));
        enemyList.add(new Enemy(str(context, R.string.enemy_dark_tanker), 40, 35, 0, 0, 5.0, 25.0, "waypoints", "knifeThrower", R.drawable.enemy_dark_tanker));
        enemyList.add(new Enemy(str(context, R.string.enemy_mummy), 40, 23, 0, 0, 6.0, 29.5, "waypoints", "stoneThrower", R.drawable.enemy_mummy));
        enemyList.add(new Enemy(str(context, R.string.enemy_skeleton), 40, 23, 0, 0, 6.0, 29.5, "waypoints", "stoneThrower", R.drawable.enemy_skeleton));
        enemyList.add(new Enemy(str(context, R.string.enemy_spider_fire), 40, 24, 0, 0, 3.2, 25.0, "waypoints", "stoneThrower", R.drawable.enemy_spider));
        enemyList.add(new Enemy(str(context, R.string.enemy_zombie_red_guard), 40, 24, 0, 2, 5.0, 30.0, "waypoints", "knifeThrower", R.drawable.enemy_zombie));
        enemyList.add(new Enemy(str(context, R.string.enemy_demonic_spider_blowing_minion), 50, 23, 0, 0, 7.0, 28.0, "waypoints", "stoneThrower", R.drawable.enemy_blowing_demonic_spider_minion));
        enemyList.add(new Enemy(str(context, R.string.enemy_demonic_spider_minion), 50, 23, 0, 0, 4.0, 28.0, "waypoints", "stoneThrower", R.drawable.enemy_blowing_demonic_spider_minion));
        enemyList.add(new Enemy(str(context, R.string.enemy_ghost_rat), 60, 25, 0, 0, 6.0, 20.0, "waypoints", "stoneThrower", R.drawable.enemy_rat_ghost));
        enemyList.add(new Enemy(str(context, R.string.enemy_spider_blow), 70, 27, 0, 0, 3.9, 30.0, "waypoints", "stoneThrower", R.drawable.enemy_spider));
        enemyList.add(new Enemy(str(context, R.string.enemy_fire_bat), 80, 40, 0, 0, 3.0, 24.5, "waypoints", "stoneThrower", R.drawable.enemy_bat));
        enemyList.add(new Enemy(str(context, R.string.enemy_harmless_tanker), 80, 0, 0, 0, 5.0, 25.0, "waypoints", "knifeThrower", R.drawable.enemy_harmless_tanker));
        enemyList.add(new Enemy(str(context, R.string.enemy_miniboss_gigaspider_critter), 80, 30, 0, 0, 3.2, 20.0, "waypoints", "stoneThrower", R.drawable.enemy_miniboss_gigaspider_critter));
        enemyList.add(new Enemy(str(context, R.string.enemy_spider_c), 80, 22, 0, 0, 4.0, 24.5, "waypoints", "stoneThrower", R.drawable.enemy_spider));
        enemyList.add(new Enemy(str(context, R.string.enemy_spider_swamp), 80, 30, 0, 0, 3.2, 30.0, "waypoints", "stoneThrower", R.drawable.enemy_spider));
        enemyList.add(new Enemy(str(context, R.string.enemy_tanker_rage_matryoshka), 80, 40, 0, 0, 5.0, 25.0, "waypoints", "knifeThrower", R.drawable.enemy_harmless_tanker));
        enemyList.add(new Enemy(str(context, R.string.enemy_armored_skeleton), 90, 25, 0, 0, 5.4, 31.0, "waypoints", "stoneThrower", R.drawable.enemy_armored_skeleton));
        enemyList.add(new Enemy(str(context, R.string.enemy_dark_skeleton), 90, 20, 0, 0, 5.45, 31.0, "waypoints", "knifeThrower", R.drawable.enemy_dark_skeleton));
        enemyList.add(new Enemy(str(context, R.string.enemy_fire_skeleton_b), 90, 30, 0, 0, 5.4, 31.0, "waypoints", "knifeThrower", R.drawable.enemy_ifrits_disciple));
        enemyList.add(new Enemy(str(context, R.string.enemy_fire_skeleton), 90, 30, 0, 0, 5.4, 31.0, "waypoints", "knifeThrower", R.drawable.enemy_ifrits_disciple));
        enemyList.add(new Enemy(str(context, R.string.enemy_tanker_helmet_matryoshka), 90, 30, 0, 0, 5.4, 31.0, "waypoints", "knifeThrower", R.drawable.enemy_helmet_skeleton));
        enemyList.add(new Enemy(str(context, R.string.enemy_zombie_guard_boss), 100, 25, 0, 2, 5.0, 25.0, "waypoints", "knifeThrower", R.drawable.enemy_zombie_b));
        enemyList.add(new Enemy(str(context, R.string.enemy_carnival_pilot_mask_skeleton), 110, 30, 0, 0, 5.4, 35.0, "waypoints", "knifeThrower", R.drawable.enemy_skeleton));
        enemyList.add(new Enemy(str(context, R.string.enemy_nature_skeleton), 110, 15, 0, 0, 5.4, 31.0, "waypoints", "knifeThrower", R.drawable.enemy_nature_skeleton));
        enemyList.add(new Enemy(str(context, R.string.enemy_demon_head), 120, 55, 0, 0, 3.0, 24.5, "waypoints", "stoneThrower", R.drawable.enemy_demon_head));
        enemyList.add(new Enemy(str(context, R.string.enemy_zombie_guard_boss_b), 120, 26, 0, 2, 5.0, 25.0, "waypoints", "knifeThrower", R.drawable.enemy_zombie_b));
        enemyList.add(new Enemy(str(context, R.string.enemy_guard_tanker_a), 130, 40, 0, 0, 5.0, 25.0, "waypoints", "knifeThrower", R.drawable.enemy_helmet_skeleton));
        enemyList.add(new Enemy(str(context, R.string.enemy_guard_tanker_b), 130, 30, 0, 0, 5.2, 25.0, "waypoints", "knifeThrower", R.drawable.enemy_helmet_skeleton));
        enemyList.add(new Enemy(str(context, R.string.enemy_jumping_fire_skeleton), 140, 40, 0, 10, 5.4, 35.0, "waypoints", "knifeThrower", R.drawable.enemy_jumping_fire_skeleton));
        enemyList.add(new Enemy(str(context, R.string.enemy_zombie_guard_boss_c), 140, 32, 0, 17, 5.0, 25.0, "waypoints", "knifeThrower", R.drawable.enemy_zombie_c));
        enemyList.add(new Enemy(str(context, R.string.enemy_carnival_bunny_mask_skeleton), 150, 16, 0, 0, 5.4, 31.0, "waypoints", "knifeThrower", R.drawable.enemy_skeleton));
        enemyList.add(new Enemy(str(context, R.string.enemy_carnival_pumpkin_mask_skeleton), 150, 30, 0, 0, 5.4, 31.0, "waypoints", "knifeThrower", R.drawable.enemy_skeleton));
        enemyList.add(new Enemy(str(context, R.string.enemy_helmet_skeleton), 150, 30, 0, 0, 5.4, 31.0, "waypoints", "knifeThrower", R.drawable.enemy_helmet_skeleton));
        enemyList.add(new Enemy(str(context, R.string.enemy_xmas_skeleton_red_warrior), 150, 30, 0, 150, 5.67, 31.0, "waypoints", "knifeThrower", R.drawable.enemy_xmas_skeleton_red_warrior));
        enemyList.add(new Enemy(str(context, R.string.enemy_jumping_skeleton), 160, 25, 0, 0, 5.4, 35.0, "waypoints", "knifeThrower", R.drawable.enemy_jumping_fire_skeleton));
        enemyList.add(new Enemy(str(context, R.string.enemy_carnival_buffoon_purple_skeleton), 170, 40, 0, 20, 5.9, 31.0, "waypoints", "knifeThrower", R.drawable.enemy_carnival_buffoon_purple_skeleton));
        enemyList.add(new Enemy(str(context, R.string.enemy_fire_skeleton_master), 170, 50, 0, 0, 5.4, 31.0, "waypoints", "knifeThrower", R.drawable.enemy_ifrits_disciple));
        enemyList.add(new Enemy(str(context, R.string.enemy_xmas_skeleton_red_mage), 170, 50, 0, 150, 5.67, 31.0, "waypoints", "knifeThrower", R.drawable.enemy_xmas_skeleton_red_warrior));
        enemyList.add(new Enemy(str(context, R.string.enemy_carcara), 200, 55, 0, 0, 3.0, 24.5, "waypoints", "stoneThrower", R.drawable.enemy_carcara));
        enemyList.add(new Enemy(str(context, R.string.enemy_fire_bat_adult), 200, 55, 0, 0, 3.0, 24.5, "waypoints", "stoneThrower", R.drawable.enemy_bat));
        enemyList.add(new Enemy(str(context, R.string.enemy_armored_axe_skeleton), 300, 30, 0, 0, 5.4, 31.0, "waypoints", "stoneThrower", R.drawable.enemy_jumping_fire_skeleton));
        enemyList.add(new Enemy(str(context, R.string.enemy_vampire), 320, 45, 0, 0, 6.0, 30.0, "waypoints", "knifeThrower", R.drawable.enemy_vampire));
        enemyList.add(new Enemy(str(context, R.string.enemy_water_vampire), 340, 45, 0, 20, 6.18, 30.0, "waypoints", "knifeThrower", R.drawable.enemy_water_vampire));
        enemyList.add(new Enemy(str(context, R.string.enemy_copy_cat), 380, 0, 0, 0, 9.0, 33.0, "waypoints", "knifeThrower", R.drawable.enemy_skeleton));
        enemyList.add(new Enemy(str(context, R.string.enemy_skeleton_b), 450, 50, 0, 0, 8.0, 31.0, "waypoints", "stoneThrower", R.drawable.enemy_skeleton));
        enemyList.add(new Enemy(str(context, R.string.enemy_mini_slime), 500, 0, 0, 0, 4.0, 15.0, "waypoints", "knifeThrower", R.drawable.enemy_mini_slime));
        enemyList.add(new Enemy(str(context, R.string.enemy_pumpkin_rat_skeleton), 500, 40, 0, 0, 7.5, 36.0, "waypoints", "stoneThrower", R.drawable.enemy_pumpkin_rat_skeleton));
        enemyList.add(new Enemy(str(context, R.string.enemy_air_elemental), 600, 0, 0, 0, 2.5, 10.0, "waypoints", "stoneThrower", R.drawable.enemy_air_elemental));
        enemyList.add(new Enemy(str(context, R.string.enemy_armored_ape_faster_weaker), 600, 0, 120, 0, 14.0, 32.0, "waypoints", "stoneThrower", R.drawable.enemy_armored_ape));
        enemyList.add(new Enemy(str(context, R.string.enemy_carnival_buffoon_green_skeleton), 600, 40, 0, 20, 5.9, 32.0, "waypoints", "stoneThrower", R.drawable.enemy_carnival_buffoon_green_skeleton));
        enemyList.add(new Enemy(str(context, R.string.enemy_carnival_captain_mask_skeleton), 600, 100, 0, 0, 5.4, 32.0, "waypoints", "knifeThrower", R.drawable.enemy_skeleton));
        enemyList.add(new Enemy(str(context, R.string.enemy_carnival_salesman_mask_skeleton), 600, 8, 0, 0, 5.4, 32.0, "waypoints", "stoneThrower", R.drawable.enemy_skeleton));
        enemyList.add(new Enemy(str(context, R.string.enemy_ice_skeleton), 600, 100, 0, 150, 5.67, 32.0, "waypoints", "stoneThrower", R.drawable.enemy_ice_skeleton));
        enemyList.add(new Enemy(str(context, R.string.enemy_ifrits_disciple), 600, 30, 0, 0, 6.24, 30.0, "waypoints", "knifeThrower", R.drawable.enemy_ifrits_disciple));
        enemyList.add(new Enemy(str(context, R.string.enemy_spider_easter), 600, 42, 0, 0, 5.0, 16.0, "waypoints", "stoneThrower", R.drawable.enemy_easter_spider));
        enemyList.add(new Enemy(str(context, R.string.enemy_xmas_skeleton_blue_helmet_ice), 600, 100, 0, 150, 5.67, 32.0, "waypoints", "stoneThrower", R.drawable.enemy_xmas_skeleton_blue_helmet_ice));
        enemyList.add(new Enemy(str(context, R.string.enemy_xmas_skeleton_blue_ice), 600, 100, 0, 150, 5.67, 32.0, "waypoints", "stoneThrower", R.drawable.enemy_xmas_skeleton_blue_helmet_ice));
        enemyList.add(new Enemy(str(context, R.string.enemy_zombie_chief), 600, 40, 0, 0, 9.0, 28.0, "waypoints", "stoneThrower", R.drawable.enemy_zombie_chief));
        enemyList.add(new Enemy(str(context, R.string.enemy_giant_demon_head), 600, 10, 0, 0, 3.0, 24.5, "waypoints", "stoneThrower", R.drawable.enemy_demon_head));
        enemyList.add(new Enemy(str(context, R.string.enemy_ice_skeleton_elite), 800, 150, 0, 250, 5.67, 32.0, "waypoints", "stoneThrower", R.drawable.enemy_ice_skeleton_elite));
        enemyList.add(new Enemy(str(context, R.string.enemy_swamp_monster), 800, 60, 0, 0, 5.0, 25.0, "waypoints", "stoneThrower", R.drawable.enemy_swamp_monster));
        enemyList.add(new Enemy(str(context, R.string.enemy_shaman_fire), 850, 60, 0, 40, 6.24, 30.0, "waypoints", "knifeThrower", R.drawable.enemy_shaman_fire));
        enemyList.add(new Enemy(str(context, R.string.enemy_shaman_nature), 850, 40, 0, 40, 6.78, 31.0, "waypoints", "knifeThrower", R.drawable.enemy_shaman_nature));
        enemyList.add(new Enemy(str(context, R.string.enemy_rat_fighter), 900, 35, 0, 0, 6.5, 38.0, "waypoints", "stoneThrower", R.drawable.enemy_rat_fighter));
        enemyList.add(new Enemy(str(context, R.string.enemy_cthulhu_imp), 1000, 35, 0, 0, 6.0, 40.0, "waypoints", "stoneThrower", R.drawable.enemy_cthulhu_imp));
        enemyList.add(new Enemy(str(context, R.string.enemy_fire_elemental), 1000, 20, 0, 0, 4.5, 30.0, "waypoints", "stoneThrower", R.drawable.enemy_fire_elemental));
        enemyList.add(new Enemy(str(context, R.string.enemy_rat_fire_mage), 1000, 80, 0, 0, 5.45, 31.0, "waypoints", "knifeThrower", R.drawable.enemy_rat_fire_mage));
        enemyList.add(new Enemy(str(context, R.string.enemy_rat_skeleton), 1000, 40, 0, 0, 7.5, 36.0, "waypoints", "stoneThrower", R.drawable.enemy_rat_skeleton));
        enemyList.add(new Enemy(str(context, R.string.enemy_rat_water_mage), 1000, 40, 0, 0, 5.4, 30.0, "waypoints", "knifeThrower", R.drawable.enemy_rat_water_mage));
        enemyList.add(new Enemy(str(context, R.string.enemy_xmas_fire_bear), 1000, 20, 0, 0, 5.4, 32.0, "waypoints", "stoneThrower", R.drawable.enemy_xmas_fire_bear));
        enemyList.add(new Enemy(str(context, R.string.enemy_xmas_skeleton_blue_mage), 1000, 40, 0, 150, 5.67, 30.0, "waypoints", "knifeThrower", R.drawable.enemy_xmas_skeleton_blue_mage));
        enemyList.add(new Enemy(str(context, R.string.enemy_rat_lancer), 1100, 60, 0, 0, 5.72, 37.5, "waypoints", "stoneThrower", R.drawable.enemy_rat_lancer));
        enemyList.add(new Enemy(str(context, R.string.enemy_easter_skeleton), 1200, 30, 0, 0, 5.4, 31.0, "waypoints", "knifeThrower", R.drawable.enemy_skeleton));
        enemyList.add(new Enemy(str(context, R.string.enemy_spider_easter_green), 1200, 42, 0, 0, 5.0, 16.0, "waypoints", "stoneThrower", R.drawable.enemy_green_easter_spider));
        enemyList.add(new Enemy(str(context, R.string.enemy_spider_easter_pink), 1200, 42, 0, 0, 5.0, 16.0, "waypoints", "stoneThrower", R.drawable.enemy_pink_easter_spider));
        enemyList.add(new Enemy(str(context, R.string.enemy_spider_gift), 1200, 42, 0, 0, 5.0, 16.0, "waypoints", "stoneThrower", R.drawable.enemy_gift_spider));
        enemyList.add(new Enemy(str(context, R.string.enemy_spider_boss), 1250, 42, 0, 0, 4.5, 30.5, "waypoints", "stoneThrower", R.drawable.enemy_spider_boss));
        enemyList.add(new Enemy(str(context, R.string.enemy_rat_black_mage), 1400, 80, 0, 0, 5.4, 35.0, "waypoints", "knifeThrower", R.drawable.enemy_rat_black_mage));
        enemyList.add(new Enemy(str(context, R.string.enemy_rat_rogue_prisoner), 1500, 0, 0, 40, 8.0, 37.0, "waypoints", "stoneThrower", R.drawable.enemy_rat_rogue_prisoner));
        enemyList.add(new Enemy(str(context, R.string.enemy_rat_rogue), 1500, 30, 0, 40, 8.48, 37.0, "waypoints", "stoneThrower", R.drawable.enemy_rat_rogue_prisoner));
        enemyList.add(new Enemy(str(context, R.string.enemy_evil_warlock), 2000, 38, 0, 0, 3.0, 30.0, "waypoints", "stoneThrower", R.drawable.enemy_evil_warlock));
        enemyList.add(new Enemy(str(context, R.string.enemy_pumpkin_skeleton), 2000, 80, 0, 50, 7.14, 36.0, "waypoints", "knifeThrower", R.drawable.enemy_pumpkin_skeleton));
        enemyList.add(new Enemy(str(context, R.string.enemy_pumpkin_water_skeleton), 2000, 80, 0, 50, 7.14, 36.0, "waypoints", "knifeThrower", R.drawable.enemy_pumpkin_water_skeleton));
        enemyList.add(new Enemy(str(context, R.string.enemy_rat_zombie_knife_guard_b), 2000, 51, 0, 25, 6.24, 38.0, "waypoints", "knifeThrower", R.drawable.enemy_rat_zombie_knife_guard));
        enemyList.add(new Enemy(str(context, R.string.enemy_rat_zombie_knife_guard), 2000, 51, 0, 25, 6.24, 38.0, "waypoints", "knifeThrower", R.drawable.enemy_rat_zombie_knife_guard));
        enemyList.add(new Enemy(str(context, R.string.enemy_giant_spider), 2100, 30, 0, 0, 3.0, 24.5, "waypoints", "stoneThrower", R.drawable.enemy_giant_spider));
        enemyList.add(new Enemy(str(context, R.string.enemy_junina_skeleton_a), 2500, 40, 0, 0, 5.78, 37.0, "waypoints", "stoneThrower", R.drawable.enemy_junina_skeleton));
        enemyList.add(new Enemy(str(context, R.string.enemy_armored_ape), 2800, 0, 120, 0, 11.0, 32.0, "waypoints", "stoneThrower", R.drawable.enemy_armored_ape));
        enemyList.add(new Enemy(str(context, R.string.enemy_ice_skeleton_wdg), 3000, 100, 0, 150, 5.67, 32.0, "waypoints", "stoneThrower", R.drawable.enemy_ice_skeleton));
        enemyList.add(new Enemy(str(context, R.string.enemy_pumpkin_zombie_rat), 3000, 40, 0, 0, 6.0, 32.0, "waypoints", "stoneThrower", R.drawable.enemy_pumpkin_rat));
        enemyList.add(new Enemy(str(context, R.string.enemy_xmas_doll_blond), 3000, 55, 0, 0, 3.0, 24.5, "waypoints", "stoneThrower", R.drawable.enemy_xmas_doll_blond));
        enemyList.add(new Enemy(str(context, R.string.enemy_xmas_doll_brunette), 3000, 55, 0, 0, 3.0, 24.5, "waypoints", "stoneThrower", R.drawable.enemy_xmas_doll_brunette));
        enemyList.add(new Enemy(str(context, R.string.enemy_xmas_green_bear_small), 3000, 50, 0, 0, 12.0, 38.0, "waypoints", "stoneThrower", R.drawable.enemy_xmas_green_bear));
        enemyList.add(new Enemy(str(context, R.string.enemy_xmas_purple_bear_small), 3000, 40, 0, 0, 6.3, 38.0, "waypoints", "stoneThrower", R.drawable.enemy_xmas_purple_bear));
        enemyList.add(new Enemy(str(context, R.string.enemy_carnival_captain_mask_necromancer), 3500, 180, 0, 70, 0.0, 31.0, "waypoints", "knifeThrower", R.drawable.enemy_carnival_captain_mask_necromancer));
        enemyList.add(new Enemy(str(context, R.string.enemy_ice_necromancer), 3500, 180, 0, 70, 0.0, 31.0, "waypoints", "knifeThrower", R.drawable.enemy_ice_necromancer));
        enemyList.add(new Enemy(str(context, R.string.enemy_junina_skeleton_b), 3500, 40, 0, 0, 7.88, 37.0, "waypoints", "stoneThrower", R.drawable.enemy_junina_skeleton));
        enemyList.add(new Enemy(str(context, R.string.enemy_junina_skeleton_poison_thrower), 3500, 15, 0, 0, 7.5, 37.0, "waypoints", "stoneThrower", R.drawable.enemy_junina_skeleton_poison_thrower));
        enemyList.add(new Enemy(str(context, R.string.enemy_rat_poison_thrower), 3500, 15, 0, 0, 7.5, 37.0, "waypoints", "stoneThrower", R.drawable.enemy_rat_poison_thrower));
        enemyList.add(new Enemy(str(context, R.string.enemy_time_patroller), 3500, 240, 0, 0, 6.5, 38.0, "waypoints", "stoneThrower", R.drawable.enemy_time_patroller));
        enemyList.add(new Enemy(str(context, R.string.enemy_xmas_pink_bear_small), 3500, 100, 0, 0, 10.0, 38.0, "waypoints", "stoneThrower", R.drawable.enemy_xmas_pink_bear));
        enemyList.add(new Enemy(str(context, R.string.enemy_grinch), 3700, 0, 250, 0, 11.0, 28.0, "waypoints", "stoneThrower", R.drawable.enemy_grinch));
        enemyList.add(new Enemy(str(context, R.string.enemy_ice_skeleton_elite_wdg), 4000, 150, 0, 250, 5.67, 32.0, "waypoints", "stoneThrower", R.drawable.enemy_ice_skeleton_elite));
        enemyList.add(new Enemy(str(context, R.string.enemy_junina_skeleton_dark_shadow), 4000, 20, 0, 0, 6.06, 29.5, "waypoints", "stoneThrower", R.drawable.enemy_junina_skeleton_poison_thrower));
        enemyList.add(new Enemy(str(context, R.string.enemy_junina_skeleton_fire), 4000, 19, 0, 0, 6.18, 29.5, "waypoints", "knifeThrower", R.drawable.enemy_junina_skeleton_poison_thrower));
        enemyList.add(new Enemy(str(context, R.string.enemy_junina_skeleton_knife_guard), 4000, 51, 0, 0, 7.2, 29.5, "waypoints", "knifeThrower", R.drawable.enemy_junina_skeleton_poison_thrower));
        enemyList.add(new Enemy(str(context, R.string.enemy_junina_skeleton_shadow), 4000, 100, 0, 0, 6.0, 29.5, "waypoints", "stoneThrower", R.drawable.enemy_junina_skeleton_poison_thrower));
        enemyList.add(new Enemy(str(context, R.string.enemy_rat_warrior), 4000, 70, 0, 0, 6.18, 39.0, "waypoints", "stoneThrower", R.drawable.enemy_rat_warrior));
        enemyList.add(new Enemy(str(context, R.string.enemy_xmas_jumping_green_bear), 4000, 70, 0, 0, 9.0, 35.0, "waypoints", "knifeThrower", R.drawable.enemy_xmas_green_bear));
        enemyList.add(new Enemy(str(context, R.string.enemy_xmas_pink_bear), 4000, 100, 0, 0, 10.0, 29.5, "waypoints", "stoneThrower", R.drawable.enemy_xmas_pink_bear));
        enemyList.add(new Enemy(str(context, R.string.enemy_xmas_purple_bear_ez), 4000, 40, 0, 0, 5.67, 35.0, "waypoints", "knifeThrower", R.drawable.enemy_xmas_purple_bear));
        enemyList.add(new Enemy(str(context, R.string.enemy_xmas_purple_bear), 4000, 100, 0, 0, 5.67, 35.0, "waypoints", "knifeThrower", R.drawable.enemy_xmas_purple_bear));
        enemyList.add(new Enemy(str(context, R.string.enemy_armored_ape_faster), 4500, 0, 120, 0, 14.0, 32.0, "waypoints", "stoneThrower", R.drawable.enemy_armored_ape));
        enemyList.add(new Enemy(str(context, R.string.enemy_fire_skeleton_elite), 4500, 50, 0, 0, 5.4, 31.0, "waypoints", "knifeThrower", R.drawable.enemy_ifrits_disciple));
        enemyList.add(new Enemy(str(context, R.string.enemy_jumping_fire_skeleton_elite), 4500, 40, 0, 10, 7.2, 35.0, "waypoints", "knifeThrower", R.drawable.enemy_jumping_fire_skeleton));
        enemyList.add(new Enemy(str(context, R.string.enemy_jumping_skeleton_elite), 4500, 60, 0, 0, 7.2, 35.0, "waypoints", "knifeThrower", R.drawable.enemy_jumping_fire_skeleton));
        enemyList.add(new Enemy(str(context, R.string.enemy_mushroom_spitter), 4500, 80, 0, 0, 6.0, 0.0, "waypoints", "knifeThrower", R.drawable.enemy_mushroom_spitter));
        enemyList.add(new Enemy(str(context, R.string.enemy_white_ape), 4700, 0, 250, 0, 11.0, 28.0, "waypoints", "stoneThrower", R.drawable.enemy_white_ape));
        enemyList.add(new Enemy(str(context, R.string.enemy_fire_ape), 5000, 0, 250, 0, 11.0, 28.0, "waypoints", "stoneThrower", R.drawable.enemy_white_ape));
        enemyList.add(new Enemy(str(context, R.string.enemy_pumpkin_skeleton_scythe), 5000, 140, 0, 50, 7.0, 36.0, "waypoints", "knifeThrower", R.drawable.enemy_pumpkin_skeleton));
        enemyList.add(new Enemy(str(context, R.string.enemy_pumpkin_water_skeleton_scythe), 5000, 85, 0, 102, 7.0, 36.0, "waypoints", "knifeThrower", R.drawable.enemy_pumpkin_water_skeleton));
        enemyList.add(new Enemy(str(context, R.string.enemy_zombie_rat), 5000, 100, 0, 0, 6.0, 32.0, "waypoints", "stoneThrower", R.drawable.enemy_zombie_rat));
        enemyList.add(new Enemy(str(context, R.string.enemy_ice_skeleton_tanker), 5500, 190, 0, 80, 5.4, 33.0, "waypoints", "knifeThrower", R.drawable.enemy_ice_skeleton_tanker));
        enemyList.add(new Enemy(str(context, R.string.enemy_nature_skeleton_elite), 5500, 45, 0, 0, 5.4, 31.0, "waypoints", "knifeThrower", R.drawable.enemy_nature_skeleton));
        enemyList.add(new Enemy(str(context, R.string.enemy_snow_monster), 6550, 80, 0, 0, 5.0, 25.0, "waypoints", "stoneThrower", R.drawable.enemy_snow_monster));
        enemyList.add(new Enemy(str(context, R.string.enemy_dark_skeleton_elite), 7500, 80, 0, 0, 5.45, 31.0, "waypoints", "knifeThrower", R.drawable.enemy_dark_skeleton));
        enemyList.add(new Enemy(str(context, R.string.enemy_xmas_skeleton_red_mage_elite), 7500, 80, 0, 150, 5.73, 31.0, "waypoints", "knifeThrower", R.drawable.enemy_xmas_skeleton_red_warrior));
        enemyList.add(new Enemy(str(context, R.string.enemy_carnival_rat_buffoon_green), 8000, 100, 0, 25, 5.46, 39.0, "waypoints", "knifeThrower", R.drawable.enemy_carnival_rat_buffoon_green));
        enemyList.add(new Enemy(str(context, R.string.enemy_carnival_rat_buffoon_purple), 8000, 100, 0, 25, 5.46, 39.0, "waypoints", "knifeThrower", R.drawable.enemy_carnival_rat_buffoon_purple));
        enemyList.add(new Enemy(str(context, R.string.enemy_rat_zombie_knife_guard_elite), 8000, 100, 0, 25, 6.24, 39.0, "waypoints", "knifeThrower", R.drawable.enemy_rat_zombie_knife_guard_elite));
        enemyList.add(new Enemy(str(context, R.string.enemy_tanker_elite_matryoshka), 8000, 70, 0, 0, 5.25, 25.0, "waypoints", "knifeThrower", R.drawable.enemy_harmless_tanker));
        enemyList.add(new Enemy(str(context, R.string.enemy_guard_tanker_elite), 9000, 70, 0, 0, 5.25, 25.0, "waypoints", "knifeThrower", R.drawable.enemy_harmless_tanker));
        enemyList.add(new Enemy(str(context, R.string.enemy_shaman_fire_elite), 9000, 60, 0, 80, 6.24, 30.0, "waypoints", "knifeThrower", R.drawable.enemy_shaman_fire));
        enemyList.add(new Enemy(str(context, R.string.enemy_shaman_nature_elite), 9000, 50, 0, 80, 9.04, 34.0, "waypoints", "knifeThrower", R.drawable.enemy_shaman_nature));
        enemyList.add(new Enemy(str(context, R.string.enemy_xmas_skeleton_red_warrior_elite), 9000, 70, 0, 150, 5.51, 25.0, "waypoints", "knifeThrower", R.drawable.enemy_xmas_skeleton_red_warrior));
        enemyList.add(new Enemy(str(context, R.string.enemy_mummy_blue_cosmos), 9500, 100, 0, 0, 5.4, 31.0, "waypoints", "knifeThrower", R.drawable.enemy_mummy));
        enemyList.add(new Enemy(str(context, R.string.enemy_mummy_gold_cosmos), 9500, 70, 0, 0, 5.67, 31.0, "waypoints", "knifeThrower", R.drawable.enemy_mummy));
        enemyList.add(new Enemy(str(context, R.string.enemy_ice_necromancer_wdg), 10000, 180, 0, 70, 0.0, 31.0, "waypoints", "knifeThrower", R.drawable.enemy_ice_necromancer));
        enemyList.add(new Enemy(str(context, R.string.enemy_xmas_fire_bear_elite), 10000, 30, 0, 0, 5.82, 31.0, "waypoints", "knifeThrower", R.drawable.enemy_xmas_fire_bear));
        enemyList.add(new Enemy(str(context, R.string.enemy_mush_vacuum), 12000, 40, 0, 0, 6.0, 0.0, "waypoints", "knifeThrower", R.drawable.enemy_mush_vacuum));
        enemyList.add(new Enemy(str(context, R.string.enemy_xmas_gift_vacuum), 12000, 40, 0, 0, 6.0, 0.0, "waypoints", "knifeThrower", R.drawable.enemy_mush_vacuum));
        enemyList.add(new Enemy(str(context, R.string.enemy_ice_skeleton_tanker_wdg), 15000, 190, 0, 80, 5.4, 33.0, "waypoints", "knifeThrower", R.drawable.enemy_ice_skeleton_tanker));
        enemyList.add(new Enemy(str(context, R.string.enemy_xmas_skeleton_blue_tanker), 15000, 190, 0, 150, 5.67, 33.0, "waypoints", "knifeThrower", R.drawable.enemy_xmas_skeleton_blue_helmet_ice));
        enemyList.add(new Enemy(str(context, R.string.enemy_evil_warlock_2), 24000, 80, 0, 0, 3.0, 35.0, "waypoints", "stoneThrower", R.drawable.enemy_evil_warlock));
        enemyList.add(new Enemy(str(context, R.string.enemy_mush_vacuum_wdg), 36000, 40, 0, 0, 6.0, 0.0, "waypoints", "knifeThrower", R.drawable.enemy_mush_vacuum));
        enemyList.add(new Enemy(str(context, R.string.enemy_wizard), 500000, 0, 0, 0, 4.0, 33.0, "waypoints", "stoneThrower", R.drawable.enemy_wizard));
        enemyList.add(new Enemy(str(context, R.string.enemy_alien), 9999999, 0, 0, 36, 7.42, 35.0, "waypoints", "knifeThrower", R.drawable.enemy_alien));
        enemyList.add(new Enemy(str(context, R.string.enemy_kingptain_dungeon43), 999999999, 600, 0, 8000, 8.0, 36.0, "waypoints", "stoneThrower", R.drawable.enemy_kingptain));
        enemyList.add(new Enemy(str(context, R.string.enemy_priest_minion), 999999999, 28, 0, 0, 8.48, 33.0, "", "", R.drawable.enemy_priest_minion));
        enemyList.add(new Enemy(str(context, R.string.enemy_time_patroller_dungeon41), 999999999, 0, 0, 36, 7.42, 35.0, "waypoints", "knifeThrower", R.drawable.enemy_time_patroller_boss));
        enemyList.add(new Enemy(str(context, R.string.enemy_time_patroller_dungeon40), 999999999, 6, 0, 36, 7.42, 35.0, "waypoints", "knifeThrower", R.drawable.enemy_time_patroller_boss));
        enemyList.add(new Enemy(str(context, R.string.enemy_ape_demon), 999999999, 0, 80, 0, 15.0, 31.0, "waypoints", "stoneThrower", R.drawable.enemy_ape));
        enemyList.add(new Enemy(str(context, R.string.enemy_ape_junina), 999999999, 0, 80, 0, 15.0, 31.0, "waypoints", "stoneThrower", R.drawable.enemy_ape_junina));
        enemyList.add(new Enemy(str(context, R.string.enemy_ape_santa), 999999999, 0, 80, 0, 15.0, 31.0, "waypoints", "stoneThrower", R.drawable.enemy_ape));
        enemyList.add(new Enemy(str(context, R.string.enemy_ape_skeleton), 999999999, 0, 5, 0, 8.0, 31.0, "waypoints", "stoneThrower", R.drawable.enemy_skeleton_ape));
        enemyList.add(new Enemy(str(context, R.string.enemy_armademon_easter), 999999999, 0, 20, 0, 9.0, 16.0, "waypoints", "stoneThrower", R.drawable.enemy_easter_armademon));
        enemyList.add(new Enemy(str(context, R.string.enemy_armademon), 999999999, 0, 20, 0, 9.0, 16.0, "waypoints", "stoneThrower", R.drawable.enemy_armademon));
        enemyList.add(new Enemy(str(context, R.string.enemy_armadillo), 999999999, 0, 1, 0, 7.0, 12.0, "waypoints", "stoneThrower", R.drawable.enemy_armadillo));
        enemyList.add(new Enemy(str(context, R.string.enemy_armadimp), 999999999, 0, 7, 0, 7.0, 12.0, "waypoints", "stoneThrower", R.drawable.enemy_armadillo));
        enemyList.add(new Enemy(str(context, R.string.enemy_beholder_witch), 999999999, 60, 0, 0, 5.2, 1.0, "waypoints", "stoneThrower", R.drawable.enemy_beholder_witch));
        enemyList.add(new Enemy(str(context, R.string.enemy_beholder), 999999999, 60, 0, 0, 5.2, 1.0, "waypoints", "stoneThrower", R.drawable.enemy_beholder));
        enemyList.add(new Enemy(str(context, R.string.enemy_cangaceiro), 999999999, 60, 20, 0, 13.52, 0.0, "waypoints", "", R.drawable.enemy_cangaceiro));
        enemyList.add(new Enemy(str(context, R.string.enemy_chest_demon_gift), 999999999, 40, 30, 0, 11.0, 20.0, "waypoints", "stoneThrower", R.drawable.enemy_chest_demon_gift));
        enemyList.add(new Enemy(str(context, R.string.enemy_chest_demon), 999999999, 40, 30, 0, 11.0, 20.0, "waypoints", "stoneThrower", R.drawable.enemy_chest_demon));
        enemyList.add(new Enemy(str(context, R.string.enemy_cthulhu), 999999999, 0, 0, 0, 5.0, 15.0, "waypoints", "stoneThrower", R.drawable.enemy_cthulhu));
        enemyList.add(new Enemy(str(context, R.string.enemy_cyclops), 999999999, 140, 0, 70, 8.0, 29.0, "waypoints", "knifeThrower", R.drawable.enemy_cyclops));
        enemyList.add(new Enemy(str(context, R.string.enemy_demon_stomper), 999999999, 0, 0, 0, 8.0, 1.0, "waypoints", "stoneThrower", R.drawable.enemy_demon_stomper));
        enemyList.add(new Enemy(str(context, R.string.enemy_demonic_spider), 999999999, 34, 0, 0, 7.0, 55.0, "waypoints", "knifeThrower", R.drawable.enemy_demonic_spider));
        enemyList.add(new Enemy(str(context, R.string.enemy_easter_demon), 999999999, 0, 80, 0, 15.0, 31.0, "waypoints", "stoneThrower", R.drawable.enemy_easter_demon));
        enemyList.add(new Enemy(str(context, R.string.enemy_final_warlock), 999999999, 250, 0, 0, 3.0, 36.0, "waypoints", "stoneThrower", R.drawable.enemy_evil_warlock));
        enemyList.add(new Enemy(str(context, R.string.enemy_fire_lord), 999999999, 110, 0, 0, 5.0, 1.0, "waypoints", "knifeThrower", R.drawable.enemy_fire_lord));
        enemyList.add(new Enemy(str(context, R.string.enemy_gigaspider), 999999999, 30, 0, 0, 5.0, 24.5, "waypoints", "stoneThrower", R.drawable.enemy_gigaspider));
        enemyList.add(new Enemy(str(context, R.string.enemy_golem), 999999999, 18, 0, 0, 7.0, 18.0, "waypoints", "knifeThrower", R.drawable.enemy_golem));
        enemyList.add(new Enemy(str(context, R.string.enemy_gorgon), 999999999, 15, 0, 0, 7.0, 35.0, "waypoints", "knifeThrower", R.drawable.enemy_gorgon));
        enemyList.add(new Enemy(str(context, R.string.enemy_ice_golem), 999999999, 18, 0, 0, 7.0, 23.0, "waypoints", "knifeThrower", R.drawable.enemy_ice_golem));
        enemyList.add(new Enemy(str(context, R.string.enemy_orc_fighter), 999999999, 120, 0, 0, 6.0, 1.0, "waypoints", "knifeThrower", R.drawable.enemy_orc_fighter));
        enemyList.add(new Enemy(str(context, R.string.enemy_slime_demon), 999999999, 44, 0, 0, 15.0, 5.0, "waypoints", "knifeThrower", R.drawable.enemy_slime_demon));
        enemyList.add(new Enemy(str(context, R.string.enemy_spidemon_higher_jump), 999999999, 23, 0, 0, 6.5, 18.0, "waypoints", "stoneThrower", R.drawable.enemy_spidemon));
        enemyList.add(new Enemy(str(context, R.string.enemy_spidemon), 999999999, 23, 0, 0, 6.5, 15.0, "waypoints", "stoneThrower", R.drawable.enemy_spidemon));
        enemyList.add(new Enemy(str(context, R.string.enemy_tombstone_mimic), 999999999, 40, 30, 0, 11.0, 20.0, "waypoints", "stoneThrower", R.drawable.enemy_tombstone_mimic));
        enemyList.add(new Enemy(str(context, R.string.enemy_vindicator_carnival), 999999999, 220, 0, 0, 5.0, 1.0, "waypoints", "knifeThrower", R.drawable.enemy_vindicator_carnival));
        enemyList.add(new Enemy(str(context, R.string.enemy_vindicator), 999999999, 220, 0, 0, 5.0, 1.0, "waypoints", "knifeThrower", R.drawable.enemy_vindicator));
        enemyList.add(new Enemy(str(context, R.string.enemy_vulkling), 999999999, 3, 0, 0, 6.0, 18.0, "waypoints", "knifeThrower", R.drawable.enemy_vulkling));
        enemyList.add(new Enemy(str(context, R.string.enemy_walker), 999999999, 0, 0, 200000, 8.0, 18.0, "waypoints", "knifeThrower", R.drawable.enemy_walker));
        enemyList.add(new Enemy(str(context, R.string.enemy_warlock_final_boss), 999999999, 0, 400, 0, 7.0, 28.0, "waypoints", "stoneThrower", R.drawable.enemy_warlock_final_boss));
        enemyList.add(new Enemy(str(context, R.string.enemy_xmas_mimic), 999999999, 40, 30, 0, 14.0, 28.0, "waypoints", "stoneThrower", R.drawable.enemy_xmas_mimic));
    }
}

