# -*- coding: utf-8 -*-
"""Generates app/src/main/assets/entity_palette.json — the category manifest that drives the
Level Editor's "Add entity" (+) menu chips.

Ground truth for "placeable" = the .ent appears in at least one bundled stock level (assets/levels/*.esc).
Ordering within a category = usage frequency across those levels (most-used first). Entities that never
appear in any stock level (~1,500 projectiles / animations / blood / character sub-parts) are treated as
effect/advanced noise and are reachable in-app only via the "All" chip, not the per-category chips.

Re-run this whenever the bundled entities or levels change:
    python tools/gen_palette.py
No arguments; paths are resolved relative to this script.
"""
import os, re, glob, json
from collections import Counter

HERE = os.path.dirname(os.path.abspath(__file__))
ASSETS = os.path.join(HERE, "..", "app", "src", "main", "assets")
LV  = os.path.join(ASSETS, "levels")
ENT = os.path.join(ASSETS, "entities")
OUT = os.path.join(ASSETS, "entity_palette.json")

palette = sorted(f for f in os.listdir(ENT) if f.endswith(".ent"))
freq = Counter()
ref_re = re.compile(r'<EntityName>([^<]+\.ent)</EntityName>')
for p in glob.glob(os.path.join(LV, "*.esc")):
    for m in ref_re.findall(open(p, encoding="utf-8", errors="ignore").read()):
        freq[m] += 1

placeable = [f for f in palette if freq.get(f, 0) > 0]
placeable.sort(key=lambda f: (-freq[f], f))               # usage desc, then name

# Category rules (first match wins). Order matters: specific types first, then logic/structural,
# then platforms, then a decor catch-all.
RULES = [
 ("doors",     ("door","portal","exit","gate","checkpoint","teleport","ladder","stair","elevator","lever","_switch","key_hole","banner_end")),
 ("hazards",   ("spike","saw","lava","instant_death","_trap","cannon","dart","crusher","buzz","guillotine","fire_jet","flame_jet","electric","acid","falling_block","spmov")),
 ("items",     ("coin","chest","powerup","power_up","_gem","gold_","key_","diamond","treasure","cake","apple","meat","_gift","present","candy","potion","heart","mana","artifact_pickup")),
 ("enemies",   ("character","_mob","mob_","miniboss","_boss","boss_","dragon","skeleton","_bat","ghost","slime","golem","zombie","spider","mummy","goblin","imp_","demon","snake","scorpion","ghoul","spawn_pool","enemy")),
 ("logic",     ("marker","invisible","push_camera","camera","black_bar","text_shadow","seam","_region","trigger","_limit","killbox","kill_box")),
 ("platforms", ("block","_tile","tiles_","platform","ground","floor","ledge","_edge","brick","_step","one_sided","base_0","base_1","pillar","column","_beam","plank","bridge","moving_","_wall","_box")),
]
def categorize(f):
    n = f.lower()
    for cat, kws in RULES:
        if any(k in n for k in kws):
            return cat
    return "decor"

order = ["platforms","enemies","items","doors","hazards","logic","decor"]
cats = {c: [] for c in order}
for f in placeable:
    cats[categorize(f)].append(f)

# Common: templates are pinned app-side; here = top placeables minus pure scene scaffolding.
SCAFFOLD = ("_marker", "text_shadow", "black_bar", "_seam", "scene_seam")
common = [f for f in placeable if not any(s in f.lower() for s in SCAFFOLD)][:40]

manifest = {
    "note": "Auto-generated by tools/gen_palette.py. 'placeable' = appears in >=1 stock level.",
    "common": common,
    "categories": [
        {"id":"platforms","label":"Platforms","items":cats["platforms"]},
        {"id":"enemies","label":"Enemies","items":cats["enemies"]},
        {"id":"items","label":"Items","items":cats["items"]},
        {"id":"doors","label":"Doors/Nav","items":cats["doors"]},
        {"id":"hazards","label":"Hazards","items":cats["hazards"]},
        {"id":"logic","label":"Logic","items":cats["logic"]},
        {"id":"decor","label":"Decor","items":cats["decor"]},
    ],
}
json.dump(manifest, open(OUT, "w", encoding="utf-8"), ensure_ascii=False, indent=1)

print(f"palette={len(palette)}  placeable={len(placeable)}  effects/hidden={len(palette)-len(placeable)}")
print(f"written: {os.path.relpath(OUT, HERE)}  ({os.path.getsize(OUT)} bytes)")
print("category sizes:", {c: len(cats[c]) for c in order}, " common:", len(common))
for c in ["logic"]:
    print(f"\n== {c} (first 15 of {len(cats[c])}) ==")
    for f in cats[c][:15]:
        print(f"   {freq[f]:5} {f}")
